Output demo.gif

Set Shell "bash"
Set FontSize 18
Set Width 900
Set Height 500
Set TypingSpeed 20ms

Type "/tmp/qr-test-vhs ~/Desktop/qr-test-imgs"
Sleep 200ms
Enter
Sleep 4s

Down
Sleep 300ms
Down
Sleep 300ms
Enter
Sleep 500ms

Down
Sleep 300ms
Enter
Sleep 2s
Enter
Sleep 500ms

Enter
Sleep 500ms
Down
Sleep 200ms
Down
Sleep 200ms
Down
Sleep 200ms
Down
Sleep 200ms
Down
Sleep 1s

Escape
Sleep 200ms
Down
Sleep 200ms
Down
Down
Down
Enter
Sleep 1s
Type "q"
Sleep 500ms
