// Every language the page speaks, as data.
//
// English is the reference: a key missing from another language falls back to
// it rather than rendering the key itself, and the self-test in i18n.js fails
// if any language is short a key, so a string cannot be added in one language
// and forgotten in the rest.
//
// Adding a language means adding one block here and nothing else.

(function (global) {
  "use strict";

  const S = {};

  // Written in each language's own words, because that is how a person finds
  // their own language in a list.
  const NAMES = {
    en: "English", it: "Italiano", es: "Español", fr: "Français",
    de: "Deutsch", pt: "Português",
  };

  S.en = {
    "qrgen.label": "Recreate the codes",
    "qrgen.download": "Download ({n})",
    "qrgen.none": "There is no code to recreate yet.",
    "qrgen.working": "Drawing the codes…",
    "drop.folderMore": "Add another folder",
    "insp.keys": "Drag a box, or drag it by its handles. Scroll to pan, pinch or ctrl-scroll to zoom, space and drag to pan. Arrows nudge, shift and arrows resize, Enter reads, Escape closes.",
    "res.summary": "{codes} codes read, {uniq} of them different.",
    "insp.zoomIn": "Zoom in",
    "insp.zoomOut": "Zoom out",
    "insp.fit": "Fit the whole picture",
    "insp.fitShort": "Fit",
    "insp.open": "Point at the code",
    "insp.title": "Point at the code",
    "insp.hint": "Drag a box around the code, then read that area. Nothing is uploaded - the crop is read here, in this tab.",
    "insp.rescan": "Read this area",
    "insp.close": "Close",
    "insp.working": "Reading that area...",
    "insp.found": "Codes read in that area: {n}",
    "insp.none": "Still nothing readable in that area. A closer or straighter photo is the next thing to try.",
    "insp.prefilled": "This box is where the scanner saw a code. Adjust it if it is off.",
    "app.tagline": "QR scanner",
    "nav.source": "Source",

    "hero.title": "Read every QR code in a folder of photos",
    "hero.sub": "Other scanners take one picture at a time. Drop a whole folder here, or a single photo, or a zip. You get every code in every image, with the file it came from.",
    "hero.trust": "Nothing is uploaded. It all runs here, in your computer.",

    "tab.images": "Images",
    "tab.camera": "Camera",

    "drop.title": "Drag & drop, or browse",
    "drop.sub": "One photo, a folder, several folders, or a zip",
    "drop.browse": "Browse files",
    "drop.folder": "Choose folder",
    "drop.paste": "Paste an image",
    "drop.shoot": "Take a photo",

    "cam.off": "The camera is off.<br>Point it at a code and it reads it live.",
    "cam.start": "Start camera",
    "cam.stop": "Stop camera",
    "cam.looking": "Looking for a code…",
    "cam.denied": "Camera permission was declined.",
    "cam.none": "No camera available here.",
    "cam.read": "Read {n} code(s) so far.",

    "res.title": "Results",
    "res.private": "100% private · runs in your browser",
    "res.empty": "Codes you scan will show up here.",
    "res.nothing": "There is nothing readable in there. It takes pictures.",
    "res.search": "Search inside the codes…",
    "res.noMatch": "No result matches that search.",
    "res.noCode": "No code found",
    "res.detected": "Code found, couldn't read it",
    "engine.loading": "starting the reader",
    "engine.ready": "reader ready",

    "work.files": "{n} files",
    "stat.images": "images",
    "stat.with": "with a code",
    "stat.codes": "codes",
    "stat.unique": "unique",
    "stat.unread": "unread",
    "stat.without": "no code",
    "stat.unopened": "unopened",

    "act.copyAll": "Copy all",
    "act.copy": "copy",
    "act.copied": "copied",
    "act.download": "Download",
    "act.clear": "Clear",
    "act.cancel": "Cancel",
    "act.clearAsk": "Throw away every result read so far?",
    "act.open": "Open",
    "act.saveContact": "Save contact",
    "act.reveal": "Reveal",
    "act.hide": "Hide",

    "rename.pattern": "New name",
    "rename.code": "The code content",
    "rename.short": "The useful part of the code",
    "rename.nameCode": "Original name + code",
    "rename.keep": "Keep the original names",
    "rename.zip": "Download ZIP ({n})",
    "rename.none": "No image here has a code to be named after.",
    "rename.preview": "will be saved as",

    "dupe.badge": "in {n} images",

    "err.advice": "Try again closer, with the code flat and evenly lit. Or crop tight around it.",
    "err.unopenable": "could not be read — unsupported format, or a damaged file",
    "err.fileAdvice": "Converting it to PNG or JPEG usually works. The local app reads formats this browser cannot.",

    "adv.localTitle": "The local app is running",
    "adv.localOn": "A local copy of the program is answering, so this page can also work on the files where they sit.",
    "adv.scan": "Scan on disk",
    "adv.paths": "Folders or files, one per line",
    "adv.recreate": "Recreate QR images",
    "adv.organize": "Sort into with_qr / without_qr",
    "adv.delete": "Delete images without a code",
    "adv.confirmOrganize": "Move every scanned image into a with_qr / without_qr folder beside it?",
    "adv.confirmDelete": "Permanently delete every scanned image that has no QR code. This cannot be undone. Continue?",
    "adv.scanFirst": "Scan on disk first.",

    "foot.privacy": "Your images never leave this device.",

    "kind.url": "Link", "kind.wifi": "Wi-Fi network", "kind.contact": "Contact",
    "kind.payment": "Payment", "kind.email": "Email", "kind.phone": "Phone number",
    "kind.sms": "Text message", "kind.location": "Location", "kind.event": "Event",
    "kind.crypto": "Crypto address", "kind.otp": "Two-factor setup",
    "kind.reference": "Reference", "kind.text": "Text",

    "f.site": "Site", "f.reference": "Reference", "f.address": "Address",
    "f.network": "Network", "f.security": "Security", "f.password": "Password",
    "f.name": "Name", "f.phone": "Phone", "f.email": "Email", "f.company": "Company",
    "f.payee": "Payee", "f.iban": "IBAN", "f.amount": "Amount",
    "f.subject": "Subject", "f.message": "Message", "f.number": "Number",
    "f.latitude": "Latitude", "f.longitude": "Longitude",
    "f.title": "Title", "f.starts": "Starts", "f.ends": "Ends", "f.where": "Where",
    "f.account": "Account", "f.issuer": "Issuer", "f.algorithm": "Algorithm",
    "f.secret": "Secret key", "f.content": "Content",
  };

  S.it = {
    "qrgen.label": "Ricrea i codici",
    "qrgen.download": "Scarica ({n})",
    "qrgen.none": "Non c'è ancora nessun codice da ricreare.",
    "qrgen.working": "Sto disegnando i codici…",
    "drop.folderMore": "Aggiungi un'altra cartella",
    "insp.keys": "Trascina un riquadro, o spostalo dalle maniglie. Scorri per muoverti, pizzica o ctrl+rotella per zoomare, spazio e trascina per spostare. Le frecce spostano, shift e frecce ridimensionano, Invio legge, Esc chiude.",
    "res.summary": "{codes} codici letti, di cui {uniq} diversi.",
    "insp.zoomIn": "Ingrandisci",
    "insp.zoomOut": "Riduci",
    "insp.fit": "Mostra tutta l'immagine",
    "insp.fitShort": "Adatta",
    "insp.open": "Indica il codice",
    "insp.title": "Indica il codice",
    "insp.hint": "Trascina un riquadro attorno al codice, poi leggi quell'area. Non viene caricato niente: il ritaglio si legge qui, in questa scheda.",
    "insp.rescan": "Leggi quest'area",
    "insp.close": "Chiudi",
    "insp.working": "Sto leggendo quell'area...",
    "insp.found": "Codici letti in quell'area: {n}",
    "insp.none": "In quell'area ancora niente di leggibile. Il passo successivo è una foto più vicina o più dritta.",
    "insp.prefilled": "Questo riquadro è dove lo scanner ha visto un codice. Correggilo se è sbagliato.",
    "app.tagline": "lettore QR",
    "nav.source": "Codice",

    "hero.title": "Leggi tutti i codici QR in una cartella di foto",
    "hero.sub": "Gli altri lettori prendono una foto alla volta. Qui trascini una cartella intera, o una sola foto, o uno zip. Ottieni ogni codice di ogni immagine, con il file da cui viene.",
    "hero.trust": "Non viene caricato niente. Funziona tutto qui, nel tuo computer.",

    "tab.images": "Immagini",
    "tab.camera": "Fotocamera",

    "drop.title": "Trascina qui, oppure scegli",
    "drop.sub": "Una foto, una cartella, più cartelle, o uno zip",
    "drop.browse": "Scegli i file",
    "drop.folder": "Scegli una cartella",
    "drop.paste": "Incolla un'immagine",
    "drop.shoot": "Scatta una foto",

    "cam.off": "La fotocamera è spenta.<br>Inquadra un codice e lo legge dal vivo.",
    "cam.start": "Accendi la fotocamera",
    "cam.stop": "Spegni la fotocamera",
    "cam.looking": "Sto cercando un codice…",
    "cam.denied": "Permesso della fotocamera negato.",
    "cam.none": "Qui non c'è una fotocamera disponibile.",
    "cam.read": "Letti {n} codici finora.",

    "res.title": "Risultati",
    "res.private": "100% privato · funziona nel tuo browser",
    "res.empty": "I codici che leggi compaiono qui.",
    "res.nothing": "Lì dentro non c'è niente da leggere. Servono immagini.",
    "res.search": "Cerca dentro i codici…",
    "res.noMatch": "Nessun risultato corrisponde alla ricerca.",
    "res.noCode": "Nessun codice trovato",
    "res.detected": "Codice trovato, non leggibile",
    "engine.loading": "avvio del lettore",
    "engine.ready": "lettore pronto",

    "work.files": "{n} file",
    "stat.images": "immagini",
    "stat.with": "con un codice",
    "stat.codes": "codici",
    "stat.unique": "univoci",
    "stat.unread": "non letti",
    "stat.without": "senza codice",
    "stat.unopened": "non aperti",

    "act.copyAll": "Copia tutto",
    "act.copy": "copia",
    "act.copied": "copiato",
    "act.download": "Scarica",
    "act.clear": "Svuota",
    "act.cancel": "Annulla",
    "act.clearAsk": "Buttare via tutti i risultati letti finora?",
    "act.open": "Apri",
    "act.saveContact": "Salva contatto",
    "act.reveal": "Mostra",
    "act.hide": "Nascondi",

    "rename.pattern": "Nuovo nome",
    "rename.code": "Il contenuto del codice",
    "rename.short": "La parte utile del codice",
    "rename.nameCode": "Nome originale + codice",
    "rename.keep": "Tieni i nomi originali",
    "rename.zip": "Scarica ZIP ({n})",
    "rename.none": "Nessuna immagine qui ha un codice da cui prendere il nome.",
    "rename.preview": "diventerà",

    "dupe.badge": "in {n} immagini",

    "err.advice": "Riprova più da vicino, con il codice dritto e illuminato in modo uniforme. Oppure ritaglia stretto attorno al codice.",
    "err.unopenable": "impossibile leggerlo — formato non supportato o file danneggiato",
    "err.fileAdvice": "Di solito basta convertirlo in PNG o JPEG. L'app locale legge formati che questo browser non apre.",

    "adv.localTitle": "L'app locale sta girando",
    "adv.localOn": "Una copia locale del programma sta rispondendo, quindi questa pagina può lavorare sui file dove si trovano.",
    "adv.scan": "Analizza su disco",
    "adv.paths": "Cartelle o file, uno per riga",
    "adv.recreate": "Rigenera le immagini QR",
    "adv.organize": "Ordina in with_qr / without_qr",
    "adv.delete": "Elimina le immagini senza codice",
    "adv.confirmOrganize": "Spostare ogni immagine analizzata in una cartella with_qr / without_qr accanto ad essa?",
    "adv.confirmDelete": "Eliminare definitivamente ogni immagine analizzata che non ha un codice QR. Non si può annullare. Procedere?",
    "adv.scanFirst": "Prima analizza su disco.",

    "foot.privacy": "Le tue immagini non lasciano mai questo dispositivo.",

    "kind.url": "Link", "kind.wifi": "Rete Wi-Fi", "kind.contact": "Contatto",
    "kind.payment": "Pagamento", "kind.email": "Email", "kind.phone": "Numero di telefono",
    "kind.sms": "Messaggio", "kind.location": "Posizione", "kind.event": "Evento",
    "kind.crypto": "Indirizzo crypto", "kind.otp": "Configurazione a due fattori",
    "kind.reference": "Riferimento", "kind.text": "Testo",

    "f.site": "Sito", "f.reference": "Riferimento", "f.address": "Indirizzo",
    "f.network": "Rete", "f.security": "Sicurezza", "f.password": "Password",
    "f.name": "Nome", "f.phone": "Telefono", "f.email": "Email", "f.company": "Azienda",
    "f.payee": "Beneficiario", "f.iban": "IBAN", "f.amount": "Importo",
    "f.subject": "Oggetto", "f.message": "Messaggio", "f.number": "Numero",
    "f.latitude": "Latitudine", "f.longitude": "Longitudine",
    "f.title": "Titolo", "f.starts": "Inizio", "f.ends": "Fine", "f.where": "Dove",
    "f.account": "Account", "f.issuer": "Servizio", "f.algorithm": "Algoritmo",
    "f.secret": "Chiave segreta", "f.content": "Contenuto",
  };

  S.es = {
    "qrgen.label": "Recrear los códigos",
    "qrgen.download": "Descargar ({n})",
    "qrgen.none": "Todavía no hay ningún código que recrear.",
    "qrgen.working": "Dibujando los códigos…",
    "drop.folderMore": "Añadir otra carpeta",
    "insp.keys": "Arrastra un recuadro o muévelo por los tiradores. Desplaza para moverte, pellizca o ctrl+rueda para acercar, espacio y arrastrar para desplazar. Las flechas mueven, shift y flechas redimensionan, Intro lee, Esc cierra.",
    "res.summary": "{codes} códigos leídos, {uniq} de ellos distintos.",
    "insp.zoomIn": "Acercar",
    "insp.zoomOut": "Alejar",
    "insp.fit": "Ver la imagen entera",
    "insp.fitShort": "Ajustar",
    "insp.open": "Señala el código",
    "insp.title": "Señala el código",
    "insp.hint": "Arrastra un recuadro alrededor del código y luego lee esa zona. No se sube nada: el recorte se lee aquí, en esta pestaña.",
    "insp.rescan": "Leer esta zona",
    "insp.close": "Cerrar",
    "insp.working": "Leyendo esa zona...",
    "insp.found": "Códigos leídos en esa zona: {n}",
    "insp.none": "En esa zona sigue sin haber nada legible. Lo siguiente que probar es una foto más cercana o más recta.",
    "insp.prefilled": "Este recuadro es donde el escáner vio un código. Ajústalo si no cuadra.",
    "app.tagline": "lector QR",
    "nav.source": "Código fuente",

    "hero.title": "Lee todos los códigos QR de una carpeta de fotos",
    "hero.sub": "Otros lectores tratan una foto cada vez. Aquí arrastras una carpeta entera, o una sola foto, o un zip. Obtienes todos los códigos de todas las imágenes, con el archivo del que vienen.",
    "hero.trust": "No se sube nada. Funciona todo aquí, en tu ordenador.",

    "tab.images": "Imágenes",
    "tab.camera": "Cámara",

    "drop.title": "Arrastra aquí, o elige",
    "drop.sub": "Una foto, una carpeta, varias carpetas, o un zip",
    "drop.browse": "Elegir archivos",
    "drop.folder": "Elegir carpeta",
    "drop.paste": "Pegar una imagen",
    "drop.shoot": "Hacer una foto",

    "cam.off": "La cámara está apagada.<br>Apúntala a un código y lo lee en directo.",
    "cam.start": "Encender la cámara",
    "cam.stop": "Apagar la cámara",
    "cam.looking": "Buscando un código…",
    "cam.denied": "Permiso de cámara denegado.",
    "cam.none": "Aquí no hay ninguna cámara disponible.",
    "cam.read": "{n} códigos leídos hasta ahora.",

    "res.title": "Resultados",
    "res.private": "100% privado · funciona en tu navegador",
    "res.empty": "Los códigos que leas aparecerán aquí.",
    "res.nothing": "Ahí dentro no hay nada que leer. Hacen falta imágenes.",
    "res.search": "Buscar dentro de los códigos…",
    "res.noMatch": "Ningún resultado coincide con la búsqueda.",
    "res.noCode": "No se encontró ningún código",
    "res.detected": "Código encontrado, no se pudo leer",
    "engine.loading": "iniciando el lector",
    "engine.ready": "lector listo",

    "work.files": "{n} archivos",
    "stat.images": "imágenes",
    "stat.with": "con código",
    "stat.codes": "códigos",
    "stat.unique": "únicos",
    "stat.unread": "sin leer",
    "stat.without": "sin código",
    "stat.unopened": "sin abrir",

    "act.copyAll": "Copiar todo",
    "act.copy": "copiar",
    "act.copied": "copiado",
    "act.download": "Descargar",
    "act.clear": "Vaciar",
    "act.cancel": "Cancelar",
    "act.clearAsk": "¿Descartar todos los resultados leídos hasta ahora?",
    "act.open": "Abrir",
    "act.saveContact": "Guardar contacto",
    "act.reveal": "Mostrar",
    "act.hide": "Ocultar",

    "rename.pattern": "Nuevo nombre",
    "rename.code": "El contenido del código",
    "rename.short": "La parte útil del código",
    "rename.nameCode": "Nombre original + código",
    "rename.keep": "Mantener los nombres originales",
    "rename.zip": "Descargar ZIP ({n})",
    "rename.none": "Ninguna imagen tiene un código del que tomar el nombre.",
    "rename.preview": "se guardará como",

    "dupe.badge": "en {n} imágenes",

    "err.advice": "Inténtalo de nuevo más cerca, con el código recto y bien iluminado. O recorta justo a su alrededor.",
    "err.unopenable": "no se ha podido leer — formato no compatible o archivo dañado",
    "err.fileAdvice": "Suele bastar con convertirlo a PNG o JPEG. La app local lee formatos que este navegador no abre.",

    "adv.localTitle": "La aplicación local está en marcha",
    "adv.localOn": "Una copia local del programa está respondiendo, así que esta página puede trabajar sobre los archivos donde están.",
    "adv.scan": "Analizar en el disco",
    "adv.paths": "Carpetas o archivos, uno por línea",
    "adv.recreate": "Regenerar las imágenes QR",
    "adv.organize": "Ordenar en with_qr / without_qr",
    "adv.delete": "Borrar las imágenes sin código",
    "adv.confirmOrganize": "¿Mover cada imagen analizada a una carpeta with_qr / without_qr junto a ella?",
    "adv.confirmDelete": "Borrar definitivamente cada imagen analizada que no tenga código QR. No se puede deshacer. ¿Continuar?",
    "adv.scanFirst": "Analiza primero en el disco.",

    "foot.privacy": "Tus imágenes nunca salen de este dispositivo.",

    "kind.url": "Enlace", "kind.wifi": "Red Wi-Fi", "kind.contact": "Contacto",
    "kind.payment": "Pago", "kind.email": "Correo", "kind.phone": "Número de teléfono",
    "kind.sms": "Mensaje", "kind.location": "Ubicación", "kind.event": "Evento",
    "kind.crypto": "Dirección cripto", "kind.otp": "Configuración de dos factores",
    "kind.reference": "Referencia", "kind.text": "Texto",

    "f.site": "Sitio", "f.reference": "Referencia", "f.address": "Dirección",
    "f.network": "Red", "f.security": "Seguridad", "f.password": "Contraseña",
    "f.name": "Nombre", "f.phone": "Teléfono", "f.email": "Correo", "f.company": "Empresa",
    "f.payee": "Beneficiario", "f.iban": "IBAN", "f.amount": "Importe",
    "f.subject": "Asunto", "f.message": "Mensaje", "f.number": "Número",
    "f.latitude": "Latitud", "f.longitude": "Longitud",
    "f.title": "Título", "f.starts": "Empieza", "f.ends": "Termina", "f.where": "Dónde",
    "f.account": "Cuenta", "f.issuer": "Servicio", "f.algorithm": "Algoritmo",
    "f.secret": "Clave secreta", "f.content": "Contenido",
  };

  S.fr = {
    "qrgen.label": "Recréer les codes",
    "qrgen.download": "Télécharger ({n})",
    "qrgen.none": "Il n'y a encore aucun code à recréer.",
    "qrgen.working": "Dessin des codes…",
    "drop.folderMore": "Ajouter un autre dossier",
    "insp.keys": "Tracez un cadre, ou déplacez-le par ses poignées. Défilez pour vous déplacer, pincez ou ctrl+molette pour zoomer, espace et glisser pour déplacer. Les flèches déplacent, maj et flèches redimensionnent, Entrée lit, Échap ferme.",
    "res.summary": "{codes} codes lus, dont {uniq} différents.",
    "insp.zoomIn": "Agrandir",
    "insp.zoomOut": "Réduire",
    "insp.fit": "Voir toute l'image",
    "insp.fitShort": "Ajuster",
    "insp.open": "Montrez le code",
    "insp.title": "Montrez le code",
    "insp.hint": "Tracez un cadre autour du code, puis lisez cette zone. Rien n'est envoyé : le recadrage est lu ici, dans cet onglet.",
    "insp.rescan": "Lire cette zone",
    "insp.close": "Fermer",
    "insp.working": "Lecture de cette zone...",
    "insp.found": "Codes lus dans cette zone : {n}",
    "insp.none": "Toujours rien de lisible dans cette zone. Essayez une photo plus proche ou plus droite.",
    "insp.prefilled": "Ce cadre est l'endroit où le scanner a vu un code. Ajustez-le s'il tombe à côté.",
    "app.tagline": "lecteur QR",
    "nav.source": "Code source",

    "hero.title": "Lisez tous les codes QR d'un dossier de photos",
    "hero.sub": "Les autres lecteurs prennent une photo à la fois. Ici vous déposez un dossier entier, ou une seule photo, ou un zip. Vous obtenez chaque code de chaque image, avec le fichier dont il vient.",
    "hero.trust": "Rien n'est envoyé. Tout fonctionne ici, sur votre ordinateur.",

    "tab.images": "Images",
    "tab.camera": "Caméra",

    "drop.title": "Déposez ici, ou parcourez",
    "drop.sub": "Une photo, un dossier, plusieurs dossiers, ou un zip",
    "drop.browse": "Choisir des fichiers",
    "drop.folder": "Choisir un dossier",
    "drop.paste": "Coller une image",
    "drop.shoot": "Prendre une photo",

    "cam.off": "La caméra est éteinte.<br>Visez un code et il est lu en direct.",
    "cam.start": "Allumer la caméra",
    "cam.stop": "Éteindre la caméra",
    "cam.looking": "Recherche d'un code…",
    "cam.denied": "Autorisation de la caméra refusée.",
    "cam.none": "Aucune caméra disponible ici.",
    "cam.read": "{n} codes lus jusqu'ici.",

    "res.title": "Résultats",
    "res.private": "100% privé · fonctionne dans votre navigateur",
    "res.empty": "Les codes que vous lisez apparaîtront ici.",
    "res.nothing": "Il n'y a rien de lisible là-dedans. Il faut des images.",
    "res.search": "Chercher dans les codes…",
    "res.noMatch": "Aucun résultat ne correspond à cette recherche.",
    "res.noCode": "Aucun code trouvé",
    "res.detected": "Code trouvé, lecture impossible",
    "engine.loading": "démarrage du lecteur",
    "engine.ready": "lecteur prêt",

    "work.files": "{n} fichiers",
    "stat.images": "images",
    "stat.with": "avec un code",
    "stat.codes": "codes",
    "stat.unique": "uniques",
    "stat.unread": "non lus",
    "stat.without": "sans code",
    "stat.unopened": "non ouverts",

    "act.copyAll": "Tout copier",
    "act.copy": "copier",
    "act.copied": "copié",
    "act.download": "Télécharger",
    "act.clear": "Vider",
    "act.cancel": "Annuler",
    "act.clearAsk": "Jeter tous les résultats lus jusqu'ici ?",
    "act.open": "Ouvrir",
    "act.saveContact": "Enregistrer le contact",
    "act.reveal": "Afficher",
    "act.hide": "Masquer",

    "rename.pattern": "Nouveau nom",
    "rename.code": "Le contenu du code",
    "rename.short": "La partie utile du code",
    "rename.nameCode": "Nom d'origine + code",
    "rename.keep": "Garder les noms d'origine",
    "rename.zip": "Télécharger le ZIP ({n})",
    "rename.none": "Aucune image ici n'a de code dont tirer un nom.",
    "rename.preview": "sera enregistré comme",

    "dupe.badge": "dans {n} images",

    "err.advice": "Réessayez de plus près, le code bien droit et uniformément éclairé. Ou recadrez au plus juste autour.",
    "err.unopenable": "lecture impossible — format non pris en charge ou fichier endommagé",
    "err.fileAdvice": "Le convertir en PNG ou JPEG suffit généralement. L'app locale lit des formats que ce navigateur n'ouvre pas.",

    "adv.localTitle": "L'application locale tourne",
    "adv.localOn": "Une copie locale du programme répond, donc cette page peut travailler sur les fichiers là où ils sont.",
    "adv.scan": "Analyser sur le disque",
    "adv.paths": "Dossiers ou fichiers, un par ligne",
    "adv.recreate": "Régénérer les images QR",
    "adv.organize": "Ranger dans with_qr / without_qr",
    "adv.delete": "Supprimer les images sans code",
    "adv.confirmOrganize": "Déplacer chaque image analysée dans un dossier with_qr / without_qr à côté d'elle ?",
    "adv.confirmDelete": "Supprimer définitivement chaque image analysée sans code QR. C'est irréversible. Continuer ?",
    "adv.scanFirst": "Analysez d'abord sur le disque.",

    "foot.privacy": "Vos images ne quittent jamais cet appareil.",

    "kind.url": "Lien", "kind.wifi": "Réseau Wi-Fi", "kind.contact": "Contact",
    "kind.payment": "Paiement", "kind.email": "E-mail", "kind.phone": "Numéro de téléphone",
    "kind.sms": "Message", "kind.location": "Position", "kind.event": "Événement",
    "kind.crypto": "Adresse crypto", "kind.otp": "Configuration à deux facteurs",
    "kind.reference": "Référence", "kind.text": "Texte",

    "f.site": "Site", "f.reference": "Référence", "f.address": "Adresse",
    "f.network": "Réseau", "f.security": "Sécurité", "f.password": "Mot de passe",
    "f.name": "Nom", "f.phone": "Téléphone", "f.email": "E-mail", "f.company": "Entreprise",
    "f.payee": "Bénéficiaire", "f.iban": "IBAN", "f.amount": "Montant",
    "f.subject": "Objet", "f.message": "Message", "f.number": "Numéro",
    "f.latitude": "Latitude", "f.longitude": "Longitude",
    "f.title": "Titre", "f.starts": "Début", "f.ends": "Fin", "f.where": "Lieu",
    "f.account": "Compte", "f.issuer": "Service", "f.algorithm": "Algorithme",
    "f.secret": "Clé secrète", "f.content": "Contenu",
  };

  S.de = {
    "qrgen.label": "Codes neu erzeugen",
    "qrgen.download": "Herunterladen ({n})",
    "qrgen.none": "Es gibt noch keinen Code zum Neuerzeugen.",
    "qrgen.working": "Die Codes werden gezeichnet…",
    "drop.folderMore": "Weiteren Ordner hinzufügen",
    "insp.keys": "Zieh einen Rahmen oder verschieb ihn an den Griffen. Scrollen bewegt, Pinch oder Strg+Rad zoomt, Leertaste und Ziehen verschiebt. Pfeile bewegen, Umschalt und Pfeile ändern die Größe, Enter liest, Esc schließt.",
    "res.summary": "{codes} Codes gelesen, davon {uniq} verschiedene.",
    "insp.zoomIn": "Vergrößern",
    "insp.zoomOut": "Verkleinern",
    "insp.fit": "Ganzes Bild anzeigen",
    "insp.fitShort": "Einpassen",
    "insp.open": "Auf den Code zeigen",
    "insp.title": "Auf den Code zeigen",
    "insp.hint": "Zieh einen Rahmen um den Code und lies dann diesen Bereich. Es wird nichts hochgeladen: der Ausschnitt wird hier gelesen, in diesem Tab.",
    "insp.rescan": "Diesen Bereich lesen",
    "insp.close": "Schließen",
    "insp.working": "Der Bereich wird gelesen...",
    "insp.found": "Gelesene Codes in diesem Bereich: {n}",
    "insp.none": "In diesem Bereich immer noch nichts Lesbares. Als Nächstes hilft ein näheres oder geraderes Foto.",
    "insp.prefilled": "Dieser Rahmen ist die Stelle, an der der Scanner einen Code gesehen hat. Korrigier ihn, falls er danebenliegt.",
    "app.tagline": "QR-Leser",
    "nav.source": "Quelltext",

    "hero.title": "Alle QR-Codes in einem Fotoordner lesen",
    "hero.sub": "Andere Leser nehmen ein Bild nach dem anderen. Hier ziehen Sie einen ganzen Ordner hinein, oder ein einzelnes Foto, oder ein ZIP. Sie bekommen jeden Code aus jedem Bild, mit der Datei dazu.",
    "hero.trust": "Nichts wird hochgeladen. Alles läuft hier, auf Ihrem Computer.",

    "tab.images": "Bilder",
    "tab.camera": "Kamera",

    "drop.title": "Hierher ziehen, oder auswählen",
    "drop.sub": "Ein Foto, ein Ordner, mehrere Ordner, oder ein ZIP",
    "drop.browse": "Dateien wählen",
    "drop.folder": "Ordner wählen",
    "drop.paste": "Bild einfügen",
    "drop.shoot": "Foto aufnehmen",

    "cam.off": "Die Kamera ist aus.<br>Richten Sie sie auf einen Code, er wird sofort gelesen.",
    "cam.start": "Kamera einschalten",
    "cam.stop": "Kamera ausschalten",
    "cam.looking": "Suche nach einem Code…",
    "cam.denied": "Kamerazugriff wurde abgelehnt.",
    "cam.none": "Hier ist keine Kamera verfügbar.",
    "cam.read": "Bisher {n} Codes gelesen.",

    "res.title": "Ergebnisse",
    "res.private": "100% privat · läuft in Ihrem Browser",
    "res.empty": "Gelesene Codes erscheinen hier.",
    "res.nothing": "Da ist nichts Lesbares drin. Es braucht Bilder.",
    "res.search": "In den Codes suchen…",
    "res.noMatch": "Kein Ergebnis passt zu dieser Suche.",
    "res.noCode": "Kein Code gefunden",
    "res.detected": "Code gefunden, nicht lesbar",
    "engine.loading": "Leser wird gestartet",
    "engine.ready": "Leser bereit",

    "work.files": "{n} Dateien",
    "stat.images": "Bilder",
    "stat.with": "mit Code",
    "stat.codes": "Codes",
    "stat.unique": "eindeutig",
    "stat.unread": "ungelesen",
    "stat.without": "ohne Code",
    "stat.unopened": "nicht geöffnet",

    "act.copyAll": "Alles kopieren",
    "act.copy": "kopieren",
    "act.copied": "kopiert",
    "act.download": "Herunterladen",
    "act.clear": "Leeren",
    "act.cancel": "Abbrechen",
    "act.clearAsk": "Alle bisher gelesenen Ergebnisse verwerfen?",
    "act.open": "Öffnen",
    "act.saveContact": "Kontakt speichern",
    "act.reveal": "Anzeigen",
    "act.hide": "Verbergen",

    "rename.pattern": "Neuer Name",
    "rename.code": "Der Inhalt des Codes",
    "rename.short": "Der nützliche Teil des Codes",
    "rename.nameCode": "Ursprünglicher Name + Code",
    "rename.keep": "Ursprüngliche Namen behalten",
    "rename.zip": "ZIP herunterladen ({n})",
    "rename.none": "Kein Bild hier hat einen Code, aus dem ein Name werden könnte.",
    "rename.preview": "wird gespeichert als",

    "dupe.badge": "in {n} Bildern",

    "err.advice": "Versuchen Sie es näher, mit dem Code gerade und gleichmäßig beleuchtet. Oder schneiden Sie eng darum zu.",
    "err.unopenable": "nicht lesbar — nicht unterstütztes Format oder beschädigte Datei",
    "err.fileAdvice": "Meist genügt es, sie in PNG oder JPEG umzuwandeln. Die lokale App liest Formate, die dieser Browser nicht öffnet.",

    "adv.localTitle": "Die lokale Anwendung läuft",
    "adv.localOn": "Eine lokale Kopie des Programms antwortet, diese Seite kann also mit den Dateien dort arbeiten, wo sie liegen.",
    "adv.scan": "Auf der Festplatte suchen",
    "adv.paths": "Ordner oder Dateien, einer pro Zeile",
    "adv.recreate": "QR-Bilder neu erzeugen",
    "adv.organize": "In with_qr / without_qr einsortieren",
    "adv.delete": "Bilder ohne Code löschen",
    "adv.confirmOrganize": "Jedes gefundene Bild in einen with_qr / without_qr Ordner daneben verschieben?",
    "adv.confirmDelete": "Jedes gefundene Bild ohne QR-Code endgültig löschen. Das lässt sich nicht rückgängig machen. Fortfahren?",
    "adv.scanFirst": "Suchen Sie zuerst auf der Festplatte.",

    "foot.privacy": "Ihre Bilder verlassen dieses Gerät nie.",

    "kind.url": "Link", "kind.wifi": "WLAN-Netz", "kind.contact": "Kontakt",
    "kind.payment": "Zahlung", "kind.email": "E-Mail", "kind.phone": "Telefonnummer",
    "kind.sms": "Nachricht", "kind.location": "Ort", "kind.event": "Termin",
    "kind.crypto": "Krypto-Adresse", "kind.otp": "Zwei-Faktor-Einrichtung",
    "kind.reference": "Referenz", "kind.text": "Text",

    "f.site": "Seite", "f.reference": "Referenz", "f.address": "Adresse",
    "f.network": "Netz", "f.security": "Sicherheit", "f.password": "Passwort",
    "f.name": "Name", "f.phone": "Telefon", "f.email": "E-Mail", "f.company": "Firma",
    "f.payee": "Empfänger", "f.iban": "IBAN", "f.amount": "Betrag",
    "f.subject": "Betreff", "f.message": "Nachricht", "f.number": "Nummer",
    "f.latitude": "Breite", "f.longitude": "Länge",
    "f.title": "Titel", "f.starts": "Beginn", "f.ends": "Ende", "f.where": "Wo",
    "f.account": "Konto", "f.issuer": "Dienst", "f.algorithm": "Algorithmus",
    "f.secret": "Geheimer Schlüssel", "f.content": "Inhalt",
  };

  S.pt = {
    "qrgen.label": "Recriar os códigos",
    "qrgen.download": "Descarregar ({n})",
    "qrgen.none": "Ainda não há nenhum código para recriar.",
    "qrgen.working": "A desenhar os códigos…",
    "drop.folderMore": "Adicionar outra pasta",
    "insp.keys": "Arraste uma caixa, ou mova-a pelas pegas. Role para se deslocar, faça pinça ou ctrl+roda para ampliar, espaço e arrastar para deslocar. As setas movem, shift e setas redimensionam, Enter lê, Esc fecha.",
    "res.summary": "{codes} códigos lidos, {uniq} deles diferentes.",
    "insp.zoomIn": "Aumentar",
    "insp.zoomOut": "Diminuir",
    "insp.fit": "Ver a imagem toda",
    "insp.fitShort": "Ajustar",
    "insp.open": "Aponte para o código",
    "insp.title": "Aponte para o código",
    "insp.hint": "Arraste uma caixa à volta do código e depois leia essa área. Nada é enviado: o recorte é lido aqui, neste separador.",
    "insp.rescan": "Ler esta área",
    "insp.close": "Fechar",
    "insp.working": "A ler essa área...",
    "insp.found": "Códigos lidos nessa área: {n}",
    "insp.none": "Nessa área continua a não haver nada legível. O passo seguinte é uma foto mais perto ou mais direita.",
    "insp.prefilled": "Esta caixa é onde o scanner viu um código. Ajuste-a se estiver ao lado.",
    "app.tagline": "leitor QR",
    "nav.source": "Código fonte",

    "hero.title": "Leia todos os códigos QR de uma pasta de fotos",
    "hero.sub": "Outros leitores tratam uma foto de cada vez. Aqui arrasta uma pasta inteira, ou uma só foto, ou um zip. Obtém todos os códigos de todas as imagens, com o ficheiro de onde vêm.",
    "hero.trust": "Nada é enviado. Funciona tudo aqui, no seu computador.",

    "tab.images": "Imagens",
    "tab.camera": "Câmara",

    "drop.title": "Arraste para aqui, ou escolha",
    "drop.sub": "Uma foto, uma pasta, várias pastas, ou um zip",
    "drop.browse": "Escolher ficheiros",
    "drop.folder": "Escolher pasta",
    "drop.paste": "Colar uma imagem",
    "drop.shoot": "Tirar uma foto",

    "cam.off": "A câmara está desligada.<br>Aponte para um código e ele é lido em direto.",
    "cam.start": "Ligar a câmara",
    "cam.stop": "Desligar a câmara",
    "cam.looking": "À procura de um código…",
    "cam.denied": "Permissão da câmara recusada.",
    "cam.none": "Não há câmara disponível aqui.",
    "cam.read": "{n} códigos lidos até agora.",

    "res.title": "Resultados",
    "res.private": "100% privado · funciona no seu navegador",
    "res.empty": "Os códigos que ler aparecem aqui.",
    "res.nothing": "Ali dentro não há nada para ler. São precisas imagens.",
    "res.search": "Procurar dentro dos códigos…",
    "res.noMatch": "Nenhum resultado corresponde a essa procura.",
    "res.noCode": "Nenhum código encontrado",
    "res.detected": "Código encontrado, não foi possível lê-lo",
    "engine.loading": "a iniciar o leitor",
    "engine.ready": "leitor pronto",

    "work.files": "{n} ficheiros",
    "stat.images": "imagens",
    "stat.with": "com código",
    "stat.codes": "códigos",
    "stat.unique": "únicos",
    "stat.unread": "por ler",
    "stat.without": "sem código",
    "stat.unopened": "não abertos",

    "act.copyAll": "Copiar tudo",
    "act.copy": "copiar",
    "act.copied": "copiado",
    "act.download": "Descarregar",
    "act.clear": "Limpar",
    "act.cancel": "Cancelar",
    "act.clearAsk": "Deitar fora todos os resultados lidos até agora?",
    "act.open": "Abrir",
    "act.saveContact": "Guardar contacto",
    "act.reveal": "Mostrar",
    "act.hide": "Esconder",

    "rename.pattern": "Novo nome",
    "rename.code": "O conteúdo do código",
    "rename.short": "A parte útil do código",
    "rename.nameCode": "Nome original + código",
    "rename.keep": "Manter os nomes originais",
    "rename.zip": "Descarregar ZIP ({n})",
    "rename.none": "Nenhuma imagem aqui tem um código de onde tirar o nome.",
    "rename.preview": "será guardado como",

    "dupe.badge": "em {n} imagens",

    "err.advice": "Tente de novo mais perto, com o código direito e bem iluminado. Ou corte justo à volta dele.",
    "err.unopenable": "não foi possível ler — formato não suportado ou ficheiro danificado",
    "err.fileAdvice": "Normalmente basta convertê-lo para PNG ou JPEG. A app local lê formatos que este navegador não abre.",

    "adv.localTitle": "A aplicação local está a correr",
    "adv.localOn": "Uma cópia local do programa está a responder, por isso esta página pode trabalhar sobre os ficheiros onde estão.",
    "adv.scan": "Analisar no disco",
    "adv.paths": "Pastas ou ficheiros, um por linha",
    "adv.recreate": "Recriar as imagens QR",
    "adv.organize": "Arrumar em with_qr / without_qr",
    "adv.delete": "Apagar as imagens sem código",
    "adv.confirmOrganize": "Mover cada imagem analisada para uma pasta with_qr / without_qr ao lado dela?",
    "adv.confirmDelete": "Apagar definitivamente cada imagem analisada sem código QR. Não se pode desfazer. Continuar?",
    "adv.scanFirst": "Analise primeiro no disco.",

    "foot.privacy": "As suas imagens nunca saem deste dispositivo.",

    "kind.url": "Ligação", "kind.wifi": "Rede Wi-Fi", "kind.contact": "Contacto",
    "kind.payment": "Pagamento", "kind.email": "Email", "kind.phone": "Número de telefone",
    "kind.sms": "Mensagem", "kind.location": "Localização", "kind.event": "Evento",
    "kind.crypto": "Endereço cripto", "kind.otp": "Configuração de dois fatores",
    "kind.reference": "Referência", "kind.text": "Texto",

    "f.site": "Site", "f.reference": "Referência", "f.address": "Endereço",
    "f.network": "Rede", "f.security": "Segurança", "f.password": "Palavra-passe",
    "f.name": "Nome", "f.phone": "Telefone", "f.email": "Email", "f.company": "Empresa",
    "f.payee": "Beneficiário", "f.iban": "IBAN", "f.amount": "Montante",
    "f.subject": "Assunto", "f.message": "Mensagem", "f.number": "Número",
    "f.latitude": "Latitude", "f.longitude": "Longitude",
    "f.title": "Título", "f.starts": "Início", "f.ends": "Fim", "f.where": "Onde",
    "f.account": "Conta", "f.issuer": "Serviço", "f.algorithm": "Algoritmo",
    "f.secret": "Chave secreta", "f.content": "Conteúdo",
  };

  global.QR_STRINGS = S;
  global.QR_LANG_NAMES = NAMES;
})(typeof globalThis !== "undefined" ? globalThis : this);
