// Every language the page speaks, as data.
//
// English is the reference: a key missing from another language falls back to
// it rather than rendering the key itself, and the self-test in i18n.js fails
// if any language is short a key, so a string cannot be added in one language
// and forgotten in the rest.
//
// Adding a language means adding one block here and nothing else.

(function (global) {
  "use strict";

  const S = {};

  // Written in each language's own words, because that is how a person finds
  // their own language in a list.
  const NAMES = {
    en: "English", it: "Italiano", es: "Español", fr: "Français",
    de: "Deutsch", pt: "Português", zh: "中文",
  };

  S.en = {
    "cam.settings": "Settings",
    "cam.found": "{n} found",
    "res.compact": "Compact",
    "act.exportAs": "Export as this format",
    "qrgen.as": "Recreate the codes in this format",
    "res.more": "More",
    "res.moreHelp": "Other formats, and turning the codes back into images",
    "cam.flip": "Flip",
    "cam.flipHelp": "Some cameras hand the picture over already mirrored. This page never mirrors it; use this if yours does.",
    "cam.auto": "Auto",
    "cam.autoHelp": "Holds the picture by itself as soon as it sees a code, then reads it properly",
    "cam.closer": "A code is in shot but too small to read. Move closer.",
    "cam.aim": "Point the camera at a QR code",
    "cam.help": "It reads by itself while you aim. Freeze the picture to draw a box around a stubborn code.",
    "cam.reading": "Reading…",
    "cam.checking": "Looking properly at what is in shot…",
    "cam.autoGot": "Read {n} of {found}",
    "cam.autoNone": "Nothing readable there. Move closer, straighten it, or draw a box yourself.",
    "cam.device": "Camera",
    "cam.deviceHelp": "An iPhone connected through Continuity Camera appears here like any other camera",
    "cam.switch": "Switch camera",
    "act.details": "Details",
    "stat.toRead": "to read",
    "res.filters": "Filter",
    "res.export": "Export",
    "rename.toggle": "Rename the files first",
    "row.flag": "Flag to check",
    "row.unflag": "Remove flag",
    "filter.flagged": "Flagged",
    "csv.loaded": "{n} codes from {file}, column “{col}”",
    "csv.clear": "Remove them",
    "csv.noHeader": "no header found, first column used",
    "csv.skipped": "{n} empty rows skipped",
    "filter.kind": "Kind",
    "filter.kindAll": "Any kind",
    "stat.uniqueHelp": "One row per distinct payload: two photos of the same code count once",
    "rename.example": "Example: {name}",
    "drop.keyboard": "You can also drop files here, or use the buttons below",
    "work.progress": "Scanning {done} of {total} images",
    "work.now": "Now: {name}",
    "work.pause": "Pause",
    "work.resume": "Resume",
    "work.paused": "Paused. {left} still to scan",
    "work.slow": "{name} is taking a while: it is large or hard to read",
    "work.done": "Finished {n} images",
    "link.title": "Where this code leads",
    "link.goes": "This link opens",
    "link.full": "Full address",
    "link.open": "Open it",
    "link.cancel": "Don't open",
    "link.warn.userinfo": "The address hides the real site before an @ sign. It opens the part AFTER the @, not the part you read first.",
    "link.warn.punycode": "The site name is written in a coded form that can imitate another name letter for letter.",
    "link.warn.insecure": "Not encrypted. Anything typed on that site travels in the open.",
    "link.warn.ipHost": "A bare address instead of a site name.",
    "link.warn.manyLabels": "A long chain of names. The real site is the part just before the ending.",
    "link.warn.veryLong": "A very long address; its beginning and end are never on screen together.",
    "trust.badge": "100% local · nothing is uploaded",
    "cam.zoneTitle": "Point the camera at a code",
    "cam.zoneSub": "Scans while you move. Nothing is recorded",
    "drop.orChoose": "Or choose from this computer",
    "cam.title": "Live scan",
    "cam.freeze": "Freeze",
    "cam.resume": "Resume",
    "cam.frozen": "Frozen. Drag a box around a code to read it.",
    "qrgen.label": "Recreate the codes",
    "qrgen.download": "Download ({n})",
    "qrgen.none": "There is no code to recreate yet.",
    "qrgen.working": "Drawing the codes…",
    "drop.folderMore": "Add another folder",
    "insp.keys": "Drag a box, or drag it by its handles. Scroll to pan, pinch or ctrl-scroll to zoom, space and drag to pan. Arrows nudge, shift and arrows resize, Enter reads, Escape closes.",
    "res.summary": "{codes} codes read, {uniq} of them different.",
    "insp.zoomIn": "Zoom in",
    "insp.zoomOut": "Zoom out",
    "insp.fit": "Fit the whole picture",
    "insp.fitShort": "Fit",
    "insp.open": "Point at the code",
    "insp.title": "Point at the code",
    "insp.hint": "Drag a box around the code, then read that area. Nothing is uploaded - the crop is read here, in this tab.",
    "insp.rescan": "Read this area",
    "insp.close": "Close",
    "insp.working": "Reading that area...",
    "insp.found": "Codes read in that area: {n}",
    "insp.none": "Still nothing readable in that area. A closer or straighter photo is the next thing to try.",
    "insp.prefilled": "This box is where the scanner saw a code. Adjust it if it is off.",
    "app.tagline": "QR scanner",
    "nav.source": "Source",

    "hero.title": "Scan every QR code in a whole folder at once, or live",
    "hero.sub": "Other scanners take one picture at a time. Drop a whole folder here, or a single photo, or a zip. You get every code in every image, with the file it came from.",
    "hero.trust": "Nothing is uploaded. It all runs here, on your computer.",

    "tab.images": "Images",
    "tab.camera": "Camera",

    "drop.title": "Drag & drop, or browse",
    "drop.sub": "One photo, a folder, several folders, or a zip",
    "drop.browse": "Browse files",
    "drop.folder": "Choose folder",
    "drop.paste": "Paste an image",
    "drop.shoot": "Take a photo",

    "cam.off": "The camera is off.<br>Point it at a code and it reads it live.",
    "cam.start": "Start camera",
    "cam.stop": "Stop camera",
    "cam.looking": "Looking for a code…",
    "cam.denied": "Camera permission was declined.",
    "cam.none": "No camera available here.",
    "cam.read": "Codes read so far: {n}",

    "res.title": "Results",
    "res.private": "100% private · runs in your browser",
    "res.empty": "Codes you scan will show up here.",
    "res.nothing": "There is nothing readable in there. It takes pictures.",
    "res.search": "Search inside the codes…",
    "res.noMatch": "No result matches that search.",
    "res.noCode": "No code found",
    "res.detected": "Code found, couldn't read it",
    "engine.loading": "starting the reader",
    "engine.ready": "reader ready",

    "work.files": "{n} files",
    "stat.images": "images",
    "stat.with": "with a code",
    "stat.codes": "codes",
    "stat.unique": "unique",
    "stat.unread": "unread",
    "stat.without": "no code",
    "stat.unopened": "unopened",

    "act.copyAll": "Copy all",
    "act.copy": "copy",
    "act.copied": "copied",
    "act.download": "Download",
    "act.clear": "Clear",
    "act.cancel": "Cancel",
    "act.clearAsk": "Throw away every result read so far?",
    "act.open": "Open",
    "act.saveContact": "Save contact",
    "act.reveal": "Reveal",
    "act.hide": "Hide",

    "rename.pattern": "New name",
    "rename.code": "The code content",
    "rename.short": "The useful part of the code",
    "rename.nameCode": "Original name + code",
    "rename.keep": "Keep the original names",
    "rename.zip": "Download ZIP ({n})",
    "rename.none": "No image here has a code to be named after.",
    "rename.preview": "will be saved as",

    "dupe.badge": "in {n} images",

    "err.advice": "Try again closer, with the code flat and evenly lit. Or crop tight around it.",
    "err.unopenable": "could not be read: unsupported format, or a damaged file",
    "err.fileAdvice": "Converting it to PNG or JPEG usually works. The local app reads formats this browser cannot.",

    "adv.localTitle": "The local app is running",
    "adv.localOn": "A local copy of the program is answering, so this page can also work on the files where they sit.",
    "adv.scan": "Scan on disk",
    "adv.paths": "Folders or files, one per line",
    "adv.recreate": "Recreate QR images",
    "adv.organize": "Sort into with_qr / without_qr",
    "adv.delete": "Delete images without a code",
    "adv.confirmOrganize": "Move every scanned image into a with_qr / without_qr folder beside it?",
    "adv.confirmDelete": "Permanently delete every scanned image that has no QR code. This cannot be undone. Continue?",
    "adv.scanFirst": "Scan on disk first.",

    "foot.privacy": "Your images never leave this device.",

    "kind.url": "Link", "kind.wifi": "Wi-Fi network", "kind.contact": "Contact",
    "kind.payment": "Payment", "kind.email": "Email", "kind.phone": "Phone number",
    "kind.sms": "Text message", "kind.location": "Location", "kind.event": "Event",
    "kind.crypto": "Crypto address", "kind.otp": "Two-factor setup",
    "kind.reference": "Reference", "kind.text": "Text",

    "f.site": "Site", "f.reference": "Reference", "f.address": "Address",
    "f.network": "Network", "f.security": "Security", "f.password": "Password",
    "f.name": "Name", "f.phone": "Phone", "f.email": "Email", "f.company": "Company",
    "f.payee": "Payee", "f.iban": "IBAN", "f.amount": "Amount",
    "f.subject": "Subject", "f.message": "Message", "f.number": "Number",
    "f.latitude": "Latitude", "f.longitude": "Longitude",
    "f.title": "Title", "f.starts": "Starts", "f.ends": "Ends", "f.where": "Where",
    "f.account": "Account", "f.issuer": "Issuer", "f.algorithm": "Algorithm",
    "f.secret": "Secret key", "f.content": "Content",
  };

  S.it = {
    "cam.settings": "Impostazioni",
    "cam.found": "{n} trovati",
    "res.compact": "Compatta",
    "act.exportAs": "Esporta in questo formato",
    "qrgen.as": "Ricrea i codici in questo formato",
    "res.more": "Altro",
    "res.moreHelp": "Altri formati, e ricreare i codici come immagini",
    "cam.flip": "Specchia",
    "cam.flipHelp": "Alcune fotocamere consegnano l'immagine già specchiata. Questa pagina non la specchia mai: usa questo se la tua lo fa.",
    "cam.auto": "Auto",
    "cam.autoHelp": "Ferma l'immagine da sola appena vede un codice, poi lo legge per bene",
    "cam.closer": "C'è un codice nell'inquadratura ma è troppo piccolo. Avvicinati.",
    "cam.aim": "Inquadra qui il tuo QR code",
    "cam.help": "Legge da sola mentre inquadri. Ferma l'immagine per disegnare un riquadro su un codice difficile.",
    "cam.reading": "Sto leggendo…",
    "cam.checking": "Guardo per bene quello che è in campo…",
    "cam.autoGot": "Letti {n} su {found}",
    "cam.autoNone": "Lì niente di leggibile. Avvicinati, raddrizzalo, oppure disegna tu un riquadro.",
    "cam.device": "Fotocamera",
    "cam.deviceHelp": "Un iPhone collegato con Fotocamera Continuity compare qui come una fotocamera qualsiasi",
    "cam.switch": "Cambia fotocamera",
    "act.details": "Dettagli",
    "stat.toRead": "da leggere",
    "res.filters": "Filtra",
    "res.export": "Esporta",
    "rename.toggle": "Rinomina i file prima",
    "row.flag": "Segna da controllare",
    "row.unflag": "Togli il segno",
    "filter.flagged": "Segnati",
    "csv.loaded": "{n} codici da {file}, colonna “{col}”",
    "csv.clear": "Toglili",
    "csv.noHeader": "nessuna intestazione trovata, usata la prima colonna",
    "csv.skipped": "{n} righe vuote saltate",
    "filter.kind": "Tipo",
    "filter.kindAll": "Qualsiasi tipo",
    "stat.uniqueHelp": "Una riga per contenuto distinto: due foto dello stesso codice contano una volta",
    "rename.example": "Esempio: {name}",
    "drop.keyboard": "Puoi anche trascinare i file qui, o usare i pulsanti sotto",
    "work.progress": "Scansione {done} di {total} immagini",
    "work.now": "In corso: {name}",
    "work.pause": "Pausa",
    "work.resume": "Riprendi",
    "work.paused": "In pausa. Ne restano {left}",
    "work.slow": "{name} ci sta mettendo molto: è grande o difficile da leggere",
    "work.done": "Finite {n} immagini",
    "link.title": "Dove porta questo codice",
    "link.goes": "Questo link apre",
    "link.full": "Indirizzo completo",
    "link.open": "Apri",
    "link.cancel": "Non aprire",
    "link.warn.userinfo": "L'indirizzo nasconde il sito vero prima di una @. Apre la parte DOPO la @, non quella che leggi per prima.",
    "link.warn.punycode": "Il nome del sito è scritto in forma codificata: può imitare un altro nome lettera per lettera.",
    "link.warn.insecure": "Non cifrato. Quello che scrivi su quel sito viaggia in chiaro.",
    "link.warn.ipHost": "Un indirizzo numerico invece di un nome di sito.",
    "link.warn.manyLabels": "Una lunga catena di nomi: il sito vero è la parte appena prima della fine.",
    "link.warn.veryLong": "Indirizzo lunghissimo: inizio e fine non stanno mai insieme sullo schermo.",
    "trust.badge": "100% in locale · niente upload",
    "cam.zoneTitle": "Inquadra un codice",
    "cam.zoneSub": "Legge mentre muovi. Non viene registrato niente",
    "drop.orChoose": "Oppure scegli da questo computer",
    "cam.title": "Scansione dal vivo",
    "cam.freeze": "Congela",
    "cam.resume": "Riprendi",
    "cam.frozen": "Immagine ferma. Trascina un riquadro attorno a un codice per leggerlo.",
    "qrgen.label": "Ricrea i codici",
    "qrgen.download": "Scarica ({n})",
    "qrgen.none": "Non c'è ancora nessun codice da ricreare.",
    "qrgen.working": "Sto disegnando i codici…",
    "drop.folderMore": "Aggiungi un'altra cartella",
    "insp.keys": "Trascina un riquadro, o spostalo dalle maniglie. Scorri per muoverti, pizzica o ctrl+rotella per zoomare, spazio e trascina per spostare. Le frecce spostano, shift e frecce ridimensionano, Invio legge, Esc chiude.",
    "res.summary": "{codes} codici letti, di cui {uniq} diversi.",
    "insp.zoomIn": "Ingrandisci",
    "insp.zoomOut": "Riduci",
    "insp.fit": "Mostra tutta l'immagine",
    "insp.fitShort": "Adatta",
    "insp.open": "Indica il codice",
    "insp.title": "Indica il codice",
    "insp.hint": "Trascina un riquadro attorno al codice, poi leggi quell'area. Non viene caricato niente: il ritaglio si legge qui, in questa scheda.",
    "insp.rescan": "Leggi quest'area",
    "insp.close": "Chiudi",
    "insp.working": "Sto leggendo quell'area...",
    "insp.found": "Codici letti in quell'area: {n}",
    "insp.none": "In quell'area ancora niente di leggibile. Il passo successivo è una foto più vicina o più dritta.",
    "insp.prefilled": "Questo riquadro è dove lo scanner ha visto un codice. Correggilo se è sbagliato.",
    "app.tagline": "lettore QR",
    "nav.source": "Codice",

    "hero.title": "Scansiona un'intera cartella di codici QR in una volta, o dal vivo",
    "hero.sub": "Gli altri lettori prendono una foto alla volta. Qui trascini una cartella intera, o una sola foto, o uno zip. Ottieni ogni codice di ogni immagine, con il file da cui viene.",
    "hero.trust": "Non viene caricato niente. Funziona tutto qui, nel tuo computer.",

    "tab.images": "Immagini",
    "tab.camera": "Fotocamera",

    "drop.title": "Trascina qui, oppure scegli",
    "drop.sub": "Una foto, una cartella, più cartelle, o uno zip",
    "drop.browse": "Scegli i file",
    "drop.folder": "Scegli una cartella",
    "drop.paste": "Incolla un'immagine",
    "drop.shoot": "Scatta una foto",

    "cam.off": "La fotocamera è spenta.<br>Inquadra un codice e lo legge dal vivo.",
    "cam.start": "Accendi la fotocamera",
    "cam.stop": "Spegni la fotocamera",
    "cam.looking": "Sto cercando un codice…",
    "cam.denied": "Permesso della fotocamera negato.",
    "cam.none": "Qui non c'è una fotocamera disponibile.",
    "cam.read": "Codici letti finora: {n}",

    "res.title": "Risultati",
    "res.private": "100% privato · funziona nel tuo browser",
    "res.empty": "I codici che leggi compaiono qui.",
    "res.nothing": "Lì dentro non c'è niente da leggere. Servono immagini.",
    "res.search": "Cerca dentro i codici…",
    "res.noMatch": "Nessun risultato corrisponde alla ricerca.",
    "res.noCode": "Nessun codice trovato",
    "res.detected": "Codice trovato, non leggibile",
    "engine.loading": "avvio del lettore",
    "engine.ready": "lettore pronto",

    "work.files": "{n} file",
    "stat.images": "immagini",
    "stat.with": "con un codice",
    "stat.codes": "codici",
    "stat.unique": "univoci",
    "stat.unread": "non letti",
    "stat.without": "senza codice",
    "stat.unopened": "non aperti",

    "act.copyAll": "Copia tutto",
    "act.copy": "copia",
    "act.copied": "copiato",
    "act.download": "Scarica",
    "act.clear": "Svuota",
    "act.cancel": "Annulla",
    "act.clearAsk": "Buttare via tutti i risultati letti finora?",
    "act.open": "Apri",
    "act.saveContact": "Salva contatto",
    "act.reveal": "Mostra",
    "act.hide": "Nascondi",

    "rename.pattern": "Nuovo nome",
    "rename.code": "Il contenuto del codice",
    "rename.short": "La parte utile del codice",
    "rename.nameCode": "Nome originale + codice",
    "rename.keep": "Tieni i nomi originali",
    "rename.zip": "Scarica ZIP ({n})",
    "rename.none": "Nessuna immagine qui ha un codice da cui prendere il nome.",
    "rename.preview": "diventerà",

    "dupe.badge": "in {n} immagini",

    "err.advice": "Riprova più da vicino, con il codice dritto e illuminato in modo uniforme. Oppure ritaglia stretto attorno al codice.",
    "err.unopenable": "impossibile leggerlo: formato non supportato o file danneggiato",
    "err.fileAdvice": "Di solito basta convertirlo in PNG o JPEG. L'app locale legge formati che questo browser non apre.",

    "adv.localTitle": "L'app locale sta girando",
    "adv.localOn": "Una copia locale del programma sta rispondendo, quindi questa pagina può lavorare sui file dove si trovano.",
    "adv.scan": "Analizza su disco",
    "adv.paths": "Cartelle o file, uno per riga",
    "adv.recreate": "Rigenera le immagini QR",
    "adv.organize": "Ordina in with_qr / without_qr",
    "adv.delete": "Elimina le immagini senza codice",
    "adv.confirmOrganize": "Spostare ogni immagine analizzata in una cartella with_qr / without_qr accanto ad essa?",
    "adv.confirmDelete": "Eliminare definitivamente ogni immagine analizzata che non ha un codice QR. Non si può annullare. Procedere?",
    "adv.scanFirst": "Prima analizza su disco.",

    "foot.privacy": "Le tue immagini non lasciano mai questo dispositivo.",

    "kind.url": "Link", "kind.wifi": "Rete Wi-Fi", "kind.contact": "Contatto",
    "kind.payment": "Pagamento", "kind.email": "Email", "kind.phone": "Numero di telefono",
    "kind.sms": "Messaggio", "kind.location": "Posizione", "kind.event": "Evento",
    "kind.crypto": "Indirizzo crypto", "kind.otp": "Configurazione a due fattori",
    "kind.reference": "Riferimento", "kind.text": "Testo",

    "f.site": "Sito", "f.reference": "Riferimento", "f.address": "Indirizzo",
    "f.network": "Rete", "f.security": "Sicurezza", "f.password": "Password",
    "f.name": "Nome", "f.phone": "Telefono", "f.email": "Email", "f.company": "Azienda",
    "f.payee": "Beneficiario", "f.iban": "IBAN", "f.amount": "Importo",
    "f.subject": "Oggetto", "f.message": "Messaggio", "f.number": "Numero",
    "f.latitude": "Latitudine", "f.longitude": "Longitudine",
    "f.title": "Titolo", "f.starts": "Inizio", "f.ends": "Fine", "f.where": "Dove",
    "f.account": "Account", "f.issuer": "Servizio", "f.algorithm": "Algoritmo",
    "f.secret": "Chiave segreta", "f.content": "Contenuto",
  };

  S.es = {
    "cam.settings": "Ajustes",
    "cam.found": "{n} encontrados",
    "res.compact": "Compacta",
    "act.exportAs": "Exportar en este formato",
    "qrgen.as": "Recrear los códigos en este formato",
    "res.more": "Más",
    "res.moreHelp": "Otros formatos, y recrear los códigos como imágenes",
    "cam.flip": "Voltear",
    "cam.flipHelp": "Algunas cámaras entregan la imagen ya invertida. Esta página nunca la invierte; usa esto si la tuya lo hace.",
    "cam.auto": "Auto",
    "cam.autoHelp": "Congela la imagen sola en cuanto ve un código, y luego lo lee bien",
    "cam.closer": "Hay un código en el encuadre pero es demasiado pequeño. Acércate.",
    "cam.aim": "Enfoca aquí tu código QR",
    "cam.help": "Lee sola mientras enfocas. Congela la imagen para dibujar un recuadro sobre un código difícil.",
    "cam.reading": "Leyendo…",
    "cam.checking": "Mirando bien lo que hay en el encuadre…",
    "cam.autoGot": "Leídos {n} de {found}",
    "cam.autoNone": "Ahí no hay nada legible. Acércate, enderézalo o dibuja tú un recuadro.",
    "cam.device": "Cámara",
    "cam.deviceHelp": "Un iPhone conectado por Cámara de Continuidad aparece aquí como cualquier otra cámara",
    "cam.switch": "Cambiar cámara",
    "act.details": "Detalles",
    "stat.toRead": "por leer",
    "res.filters": "Filtrar",
    "res.export": "Exportar",
    "rename.toggle": "Renombrar los archivos antes",
    "row.flag": "Marcar para revisar",
    "row.unflag": "Quitar la marca",
    "filter.flagged": "Marcados",
    "csv.loaded": "{n} códigos de {file}, columna «{col}»",
    "csv.clear": "Quitarlos",
    "csv.noHeader": "sin encabezado, se usó la primera columna",
    "csv.skipped": "{n} filas vacías omitidas",
    "filter.kind": "Tipo",
    "filter.kindAll": "Cualquier tipo",
    "stat.uniqueHelp": "Una fila por contenido distinto: dos fotos del mismo código cuentan una vez",
    "rename.example": "Ejemplo: {name}",
    "drop.keyboard": "También puedes arrastrar archivos aquí, o usar los botones de abajo",
    "work.progress": "Escaneando {done} de {total} imágenes",
    "work.now": "En curso: {name}",
    "work.pause": "Pausa",
    "work.resume": "Reanudar",
    "work.paused": "En pausa. Quedan {left}",
    "work.slow": "{name} está tardando: es grande o difícil de leer",
    "work.done": "Terminadas {n} imágenes",
    "link.title": "Adónde lleva este código",
    "link.goes": "Este enlace abre",
    "link.full": "Dirección completa",
    "link.open": "Abrir",
    "link.cancel": "No abrir",
    "link.warn.userinfo": "La dirección esconde el sitio real antes de una @. Abre la parte DESPUÉS de la @, no la que lees primero.",
    "link.warn.punycode": "El nombre del sitio está en forma codificada: puede imitar otro nombre letra por letra.",
    "link.warn.insecure": "Sin cifrar. Lo que escribas en ese sitio viaja en claro.",
    "link.warn.ipHost": "Una dirección numérica en lugar de un nombre de sitio.",
    "link.warn.manyLabels": "Una larga cadena de nombres: el sitio real es la parte justo antes del final.",
    "link.warn.veryLong": "Dirección larguísima: su principio y su final nunca están juntos en pantalla.",
    "trust.badge": "100% local · no se sube nada",
    "cam.zoneTitle": "Enfoca un código",
    "cam.zoneSub": "Lee mientras mueves. No se graba nada",
    "drop.orChoose": "O elige desde este ordenador",
    "cam.title": "Escaneo en vivo",
    "cam.freeze": "Congelar",
    "cam.resume": "Reanudar",
    "cam.frozen": "Imagen fija. Arrastra un recuadro alrededor de un código para leerlo.",
    "qrgen.label": "Recrear los códigos",
    "qrgen.download": "Descargar ({n})",
    "qrgen.none": "Todavía no hay ningún código que recrear.",
    "qrgen.working": "Dibujando los códigos…",
    "drop.folderMore": "Añadir otra carpeta",
    "insp.keys": "Arrastra un recuadro o muévelo por los tiradores. Desplaza para moverte, pellizca o ctrl+rueda para acercar, espacio y arrastrar para desplazar. Las flechas mueven, shift y flechas redimensionan, Intro lee, Esc cierra.",
    "res.summary": "{codes} códigos leídos, {uniq} de ellos distintos.",
    "insp.zoomIn": "Acercar",
    "insp.zoomOut": "Alejar",
    "insp.fit": "Ver la imagen entera",
    "insp.fitShort": "Ajustar",
    "insp.open": "Señala el código",
    "insp.title": "Señala el código",
    "insp.hint": "Arrastra un recuadro alrededor del código y luego lee esa zona. No se sube nada: el recorte se lee aquí, en esta pestaña.",
    "insp.rescan": "Leer esta zona",
    "insp.close": "Cerrar",
    "insp.working": "Leyendo esa zona...",
    "insp.found": "Códigos leídos en esa zona: {n}",
    "insp.none": "En esa zona sigue sin haber nada legible. Lo siguiente que probar es una foto más cercana o más recta.",
    "insp.prefilled": "Este recuadro es donde el escáner vio un código. Ajústalo si no cuadra.",
    "app.tagline": "lector QR",
    "nav.source": "Código fuente",

    "hero.title": "Escanea una carpeta entera de códigos QR de una vez, o en vivo",
    "hero.sub": "Otros lectores tratan una foto cada vez. Aquí arrastras una carpeta entera, o una sola foto, o un zip. Obtienes todos los códigos de todas las imágenes, con el archivo del que vienen.",
    "hero.trust": "No se sube nada. Funciona todo aquí, en tu ordenador.",

    "tab.images": "Imágenes",
    "tab.camera": "Cámara",

    "drop.title": "Arrastra aquí, o elige",
    "drop.sub": "Una foto, una carpeta, varias carpetas, o un zip",
    "drop.browse": "Elegir archivos",
    "drop.folder": "Elegir carpeta",
    "drop.paste": "Pegar una imagen",
    "drop.shoot": "Hacer una foto",

    "cam.off": "La cámara está apagada.<br>Apúntala a un código y lo lee en directo.",
    "cam.start": "Encender la cámara",
    "cam.stop": "Apagar la cámara",
    "cam.looking": "Buscando un código…",
    "cam.denied": "Permiso de cámara denegado.",
    "cam.none": "Aquí no hay ninguna cámara disponible.",
    "cam.read": "Códigos leídos hasta ahora: {n}",

    "res.title": "Resultados",
    "res.private": "100% privado · funciona en tu navegador",
    "res.empty": "Los códigos que leas aparecerán aquí.",
    "res.nothing": "Ahí dentro no hay nada que leer. Hacen falta imágenes.",
    "res.search": "Buscar dentro de los códigos…",
    "res.noMatch": "Ningún resultado coincide con la búsqueda.",
    "res.noCode": "No se encontró ningún código",
    "res.detected": "Código encontrado, no se pudo leer",
    "engine.loading": "iniciando el lector",
    "engine.ready": "lector listo",

    "work.files": "{n} archivos",
    "stat.images": "imágenes",
    "stat.with": "con código",
    "stat.codes": "códigos",
    "stat.unique": "únicos",
    "stat.unread": "sin leer",
    "stat.without": "sin código",
    "stat.unopened": "sin abrir",

    "act.copyAll": "Copiar todo",
    "act.copy": "copiar",
    "act.copied": "copiado",
    "act.download": "Descargar",
    "act.clear": "Vaciar",
    "act.cancel": "Cancelar",
    "act.clearAsk": "¿Descartar todos los resultados leídos hasta ahora?",
    "act.open": "Abrir",
    "act.saveContact": "Guardar contacto",
    "act.reveal": "Mostrar",
    "act.hide": "Ocultar",

    "rename.pattern": "Nuevo nombre",
    "rename.code": "El contenido del código",
    "rename.short": "La parte útil del código",
    "rename.nameCode": "Nombre original + código",
    "rename.keep": "Mantener los nombres originales",
    "rename.zip": "Descargar ZIP ({n})",
    "rename.none": "Ninguna imagen tiene un código del que tomar el nombre.",
    "rename.preview": "se guardará como",

    "dupe.badge": "en {n} imágenes",

    "err.advice": "Inténtalo de nuevo más cerca, con el código recto y bien iluminado. O recorta justo a su alrededor.",
    "err.unopenable": "no se ha podido leer: formato no compatible o archivo dañado",
    "err.fileAdvice": "Suele bastar con convertirlo a PNG o JPEG. La app local lee formatos que este navegador no abre.",

    "adv.localTitle": "La aplicación local está en marcha",
    "adv.localOn": "Una copia local del programa está respondiendo, así que esta página puede trabajar sobre los archivos donde están.",
    "adv.scan": "Analizar en el disco",
    "adv.paths": "Carpetas o archivos, uno por línea",
    "adv.recreate": "Regenerar las imágenes QR",
    "adv.organize": "Ordenar en with_qr / without_qr",
    "adv.delete": "Borrar las imágenes sin código",
    "adv.confirmOrganize": "¿Mover cada imagen analizada a una carpeta with_qr / without_qr junto a ella?",
    "adv.confirmDelete": "Borrar definitivamente cada imagen analizada que no tenga código QR. No se puede deshacer. ¿Continuar?",
    "adv.scanFirst": "Analiza primero en el disco.",

    "foot.privacy": "Tus imágenes nunca salen de este dispositivo.",

    "kind.url": "Enlace", "kind.wifi": "Red Wi-Fi", "kind.contact": "Contacto",
    "kind.payment": "Pago", "kind.email": "Correo", "kind.phone": "Número de teléfono",
    "kind.sms": "Mensaje", "kind.location": "Ubicación", "kind.event": "Evento",
    "kind.crypto": "Dirección cripto", "kind.otp": "Configuración de dos factores",
    "kind.reference": "Referencia", "kind.text": "Texto",

    "f.site": "Sitio", "f.reference": "Referencia", "f.address": "Dirección",
    "f.network": "Red", "f.security": "Seguridad", "f.password": "Contraseña",
    "f.name": "Nombre", "f.phone": "Teléfono", "f.email": "Correo", "f.company": "Empresa",
    "f.payee": "Beneficiario", "f.iban": "IBAN", "f.amount": "Importe",
    "f.subject": "Asunto", "f.message": "Mensaje", "f.number": "Número",
    "f.latitude": "Latitud", "f.longitude": "Longitud",
    "f.title": "Título", "f.starts": "Empieza", "f.ends": "Termina", "f.where": "Dónde",
    "f.account": "Cuenta", "f.issuer": "Servicio", "f.algorithm": "Algoritmo",
    "f.secret": "Clave secreta", "f.content": "Contenido",
  };

  S.fr = {
    "cam.settings": "Réglages",
    "cam.found": "{n} trouvés",
    "res.compact": "Compacte",
    "act.exportAs": "Exporter dans ce format",
    "qrgen.as": "Recréer les codes dans ce format",
    "res.more": "Plus",
    "res.moreHelp": "Autres formats, et recréer les codes en images",
    "cam.flip": "Miroir",
    "cam.flipHelp": "Certaines caméras livrent l'image déjà en miroir. Cette page ne la reflète jamais ; utilisez ceci si la vôtre le fait.",
    "cam.auto": "Auto",
    "cam.autoHelp": "Fige l'image dès qu'il voit un code, puis le lit correctement",
    "cam.closer": "Un code est dans le cadre mais trop petit. Approchez-vous.",
    "cam.aim": "Cadrez votre QR code ici",
    "cam.help": "Elle lit toute seule pendant que vous cadrez. Figez l'image pour tracer un cadre autour d'un code récalcitrant.",
    "cam.reading": "Lecture…",
    "cam.checking": "Lecture attentive de ce qui est dans le cadre…",
    "cam.autoGot": "{n} lus sur {found}",
    "cam.autoNone": "Rien de lisible là. Approchez-vous, redressez-le, ou tracez un cadre.",
    "cam.device": "Caméra",
    "cam.deviceHelp": "Un iPhone connecté via Caméra Continuité apparaît ici comme n'importe quelle caméra",
    "cam.switch": "Changer de caméra",
    "act.details": "Détails",
    "stat.toRead": "à lire",
    "res.filters": "Filtrer",
    "res.export": "Exporter",
    "rename.toggle": "Renommer les fichiers d'abord",
    "row.flag": "Marquer à vérifier",
    "row.unflag": "Retirer la marque",
    "filter.flagged": "Marqués",
    "csv.loaded": "{n} codes de {file}, colonne « {col} »",
    "csv.clear": "Les retirer",
    "csv.noHeader": "aucun en-tête trouvé, première colonne utilisée",
    "csv.skipped": "{n} lignes vides ignorées",
    "filter.kind": "Type",
    "filter.kindAll": "Tous les types",
    "stat.uniqueHelp": "Une ligne par contenu distinct : deux photos du même code comptent une fois",
    "rename.example": "Exemple : {name}",
    "drop.keyboard": "Vous pouvez aussi déposer des fichiers ici, ou utiliser les boutons ci-dessous",
    "work.progress": "Analyse de {done} sur {total} images",
    "work.now": "En cours : {name}",
    "work.pause": "Pause",
    "work.resume": "Reprendre",
    "work.paused": "En pause. Il en reste {left}",
    "work.slow": "{name} prend du temps : elle est grande ou difficile à lire",
    "work.done": "{n} images terminées",
    "link.title": "Où mène ce code",
    "link.goes": "Ce lien ouvre",
    "link.full": "Adresse complète",
    "link.open": "Ouvrir",
    "link.cancel": "Ne pas ouvrir",
    "link.warn.userinfo": "L'adresse cache le vrai site avant un @. Elle ouvre la partie APRÈS le @, pas celle que vous lisez d'abord.",
    "link.warn.punycode": "Le nom du site est écrit sous forme codée : il peut imiter un autre nom lettre par lettre.",
    "link.warn.insecure": "Non chiffré. Ce que vous tapez sur ce site circule en clair.",
    "link.warn.ipHost": "Une adresse numérique au lieu d'un nom de site.",
    "link.warn.manyLabels": "Une longue chaîne de noms : le vrai site est la partie juste avant la fin.",
    "link.warn.veryLong": "Adresse très longue : son début et sa fin ne sont jamais visibles ensemble.",
    "trust.badge": "100% local · rien n'est envoyé",
    "cam.zoneTitle": "Visez un code",
    "cam.zoneSub": "Lit pendant que vous bougez. Rien n'est enregistré",
    "drop.orChoose": "Ou choisissez sur cet ordinateur",
    "cam.title": "Scan en direct",
    "cam.freeze": "Figer",
    "cam.resume": "Reprendre",
    "cam.frozen": "Image figée. Tracez un cadre autour d'un code pour le lire.",
    "qrgen.label": "Recréer les codes",
    "qrgen.download": "Télécharger ({n})",
    "qrgen.none": "Il n'y a encore aucun code à recréer.",
    "qrgen.working": "Dessin des codes…",
    "drop.folderMore": "Ajouter un autre dossier",
    "insp.keys": "Tracez un cadre, ou déplacez-le par ses poignées. Défilez pour vous déplacer, pincez ou ctrl+molette pour zoomer, espace et glisser pour déplacer. Les flèches déplacent, maj et flèches redimensionnent, Entrée lit, Échap ferme.",
    "res.summary": "{codes} codes lus, dont {uniq} différents.",
    "insp.zoomIn": "Agrandir",
    "insp.zoomOut": "Réduire",
    "insp.fit": "Voir toute l'image",
    "insp.fitShort": "Ajuster",
    "insp.open": "Montrez le code",
    "insp.title": "Montrez le code",
    "insp.hint": "Tracez un cadre autour du code, puis lisez cette zone. Rien n'est envoyé : le recadrage est lu ici, dans cet onglet.",
    "insp.rescan": "Lire cette zone",
    "insp.close": "Fermer",
    "insp.working": "Lecture de cette zone...",
    "insp.found": "Codes lus dans cette zone : {n}",
    "insp.none": "Toujours rien de lisible dans cette zone. Essayez une photo plus proche ou plus droite.",
    "insp.prefilled": "Ce cadre est l'endroit où le scanner a vu un code. Ajustez-le s'il tombe à côté.",
    "app.tagline": "lecteur QR",
    "nav.source": "Code source",

    "hero.title": "Scannez un dossier entier de codes QR en une fois, ou en direct",
    "hero.sub": "Les autres lecteurs prennent une photo à la fois. Ici vous déposez un dossier entier, ou une seule photo, ou un zip. Vous obtenez chaque code de chaque image, avec le fichier dont il vient.",
    "hero.trust": "Rien n'est envoyé. Tout fonctionne ici, sur votre ordinateur.",

    "tab.images": "Images",
    "tab.camera": "Caméra",

    "drop.title": "Déposez ici, ou parcourez",
    "drop.sub": "Une photo, un dossier, plusieurs dossiers, ou un zip",
    "drop.browse": "Choisir des fichiers",
    "drop.folder": "Choisir un dossier",
    "drop.paste": "Coller une image",
    "drop.shoot": "Prendre une photo",

    "cam.off": "La caméra est éteinte.<br>Visez un code et il est lu en direct.",
    "cam.start": "Allumer la caméra",
    "cam.stop": "Éteindre la caméra",
    "cam.looking": "Recherche d'un code…",
    "cam.denied": "Autorisation de la caméra refusée.",
    "cam.none": "Aucune caméra disponible ici.",
    "cam.read": "Codes lus jusqu'ici : {n}",

    "res.title": "Résultats",
    "res.private": "100% privé · fonctionne dans votre navigateur",
    "res.empty": "Les codes que vous lisez apparaîtront ici.",
    "res.nothing": "Il n'y a rien de lisible là-dedans. Il faut des images.",
    "res.search": "Chercher dans les codes…",
    "res.noMatch": "Aucun résultat ne correspond à cette recherche.",
    "res.noCode": "Aucun code trouvé",
    "res.detected": "Code trouvé, lecture impossible",
    "engine.loading": "démarrage du lecteur",
    "engine.ready": "lecteur prêt",

    "work.files": "{n} fichiers",
    "stat.images": "images",
    "stat.with": "avec un code",
    "stat.codes": "codes",
    "stat.unique": "uniques",
    "stat.unread": "non lus",
    "stat.without": "sans code",
    "stat.unopened": "non ouverts",

    "act.copyAll": "Tout copier",
    "act.copy": "copier",
    "act.copied": "copié",
    "act.download": "Télécharger",
    "act.clear": "Vider",
    "act.cancel": "Annuler",
    "act.clearAsk": "Jeter tous les résultats lus jusqu'ici ?",
    "act.open": "Ouvrir",
    "act.saveContact": "Enregistrer le contact",
    "act.reveal": "Afficher",
    "act.hide": "Masquer",

    "rename.pattern": "Nouveau nom",
    "rename.code": "Le contenu du code",
    "rename.short": "La partie utile du code",
    "rename.nameCode": "Nom d'origine + code",
    "rename.keep": "Garder les noms d'origine",
    "rename.zip": "Télécharger le ZIP ({n})",
    "rename.none": "Aucune image ici n'a de code dont tirer un nom.",
    "rename.preview": "sera enregistré comme",

    "dupe.badge": "dans {n} images",

    "err.advice": "Réessayez de plus près, le code bien droit et uniformément éclairé. Ou recadrez au plus juste autour.",
    "err.unopenable": "lecture impossible : format non pris en charge ou fichier endommagé",
    "err.fileAdvice": "Le convertir en PNG ou JPEG suffit généralement. L'app locale lit des formats que ce navigateur n'ouvre pas.",

    "adv.localTitle": "L'application locale tourne",
    "adv.localOn": "Une copie locale du programme répond, donc cette page peut travailler sur les fichiers là où ils sont.",
    "adv.scan": "Analyser sur le disque",
    "adv.paths": "Dossiers ou fichiers, un par ligne",
    "adv.recreate": "Régénérer les images QR",
    "adv.organize": "Ranger dans with_qr / without_qr",
    "adv.delete": "Supprimer les images sans code",
    "adv.confirmOrganize": "Déplacer chaque image analysée dans un dossier with_qr / without_qr à côté d'elle ?",
    "adv.confirmDelete": "Supprimer définitivement chaque image analysée sans code QR. C'est irréversible. Continuer ?",
    "adv.scanFirst": "Analysez d'abord sur le disque.",

    "foot.privacy": "Vos images ne quittent jamais cet appareil.",

    "kind.url": "Lien", "kind.wifi": "Réseau Wi-Fi", "kind.contact": "Contact",
    "kind.payment": "Paiement", "kind.email": "E-mail", "kind.phone": "Numéro de téléphone",
    "kind.sms": "Message", "kind.location": "Position", "kind.event": "Événement",
    "kind.crypto": "Adresse crypto", "kind.otp": "Configuration à deux facteurs",
    "kind.reference": "Référence", "kind.text": "Texte",

    "f.site": "Site", "f.reference": "Référence", "f.address": "Adresse",
    "f.network": "Réseau", "f.security": "Sécurité", "f.password": "Mot de passe",
    "f.name": "Nom", "f.phone": "Téléphone", "f.email": "E-mail", "f.company": "Entreprise",
    "f.payee": "Bénéficiaire", "f.iban": "IBAN", "f.amount": "Montant",
    "f.subject": "Objet", "f.message": "Message", "f.number": "Numéro",
    "f.latitude": "Latitude", "f.longitude": "Longitude",
    "f.title": "Titre", "f.starts": "Début", "f.ends": "Fin", "f.where": "Lieu",
    "f.account": "Compte", "f.issuer": "Service", "f.algorithm": "Algorithme",
    "f.secret": "Clé secrète", "f.content": "Contenu",
  };

  S.de = {
    "cam.settings": "Einstellungen",
    "cam.found": "{n} gefunden",
    "res.compact": "Kompakt",
    "act.exportAs": "In diesem Format exportieren",
    "qrgen.as": "Codes in diesem Format erzeugen",
    "res.more": "Mehr",
    "res.moreHelp": "Andere Formate, und die Codes wieder als Bilder",
    "cam.flip": "Spiegeln",
    "cam.flipHelp": "Manche Kameras liefern das Bild bereits gespiegelt. Diese Seite spiegelt nie; nutze das, falls deine es tut.",
    "cam.auto": "Auto",
    "cam.autoHelp": "Friert das Bild selbst ein, sobald ein Code auftaucht, und liest ihn dann gründlich",
    "cam.closer": "Ein Code ist im Bild, aber zu klein. Geh näher ran.",
    "cam.aim": "Richte die Kamera auf einen QR-Code",
    "cam.help": "Sie liest von selbst, während du zielst. Friere das Bild ein, um einen Rahmen um einen hartnäckigen Code zu ziehen.",
    "cam.reading": "Wird gelesen…",
    "cam.checking": "Was im Bild ist, wird gründlich gelesen…",
    "cam.autoGot": "{n} von {found} gelesen",
    "cam.autoNone": "Dort nichts Lesbares. Näher rangehen, gerade halten, oder selbst einen Rahmen ziehen.",
    "cam.device": "Kamera",
    "cam.deviceHelp": "Ein über Integrationskamera verbundenes iPhone erscheint hier wie jede andere Kamera",
    "cam.switch": "Kamera wechseln",
    "act.details": "Details",
    "stat.toRead": "zu lesen",
    "res.filters": "Filtern",
    "res.export": "Exportieren",
    "rename.toggle": "Dateien vorher umbenennen",
    "row.flag": "Zum Prüfen markieren",
    "row.unflag": "Markierung entfernen",
    "filter.flagged": "Markiert",
    "csv.loaded": "{n} Codes aus {file}, Spalte „{col}“",
    "csv.clear": "Entfernen",
    "csv.noHeader": "keine Kopfzeile gefunden, erste Spalte benutzt",
    "csv.skipped": "{n} leere Zeilen übersprungen",
    "filter.kind": "Art",
    "filter.kindAll": "Jede Art",
    "stat.uniqueHelp": "Eine Zeile pro verschiedenem Inhalt: zwei Fotos desselben Codes zählen einmal",
    "rename.example": "Beispiel: {name}",
    "drop.keyboard": "Du kannst Dateien auch hierher ziehen oder die Schaltflächen unten benutzen",
    "work.progress": "{done} von {total} Bildern werden gelesen",
    "work.now": "Gerade: {name}",
    "work.pause": "Pause",
    "work.resume": "Fortsetzen",
    "work.paused": "Pausiert. Noch {left}",
    "work.slow": "{name} dauert lange: groß oder schwer zu lesen",
    "work.done": "{n} Bilder fertig",
    "link.title": "Wohin dieser Code führt",
    "link.goes": "Dieser Link öffnet",
    "link.full": "Vollständige Adresse",
    "link.open": "Öffnen",
    "link.cancel": "Nicht öffnen",
    "link.warn.userinfo": "Die Adresse verbirgt die echte Seite vor einem @. Geöffnet wird der Teil NACH dem @, nicht der, den du zuerst liest.",
    "link.warn.punycode": "Der Seitenname steht in kodierter Form: er kann einen anderen Namen Buchstabe für Buchstabe nachahmen.",
    "link.warn.insecure": "Unverschlüsselt. Was du dort eingibst, geht im Klartext über die Leitung.",
    "link.warn.ipHost": "Eine nackte Zahlenadresse statt eines Seitennamens.",
    "link.warn.manyLabels": "Eine lange Namenskette: die echte Seite ist der Teil kurz vor dem Ende.",
    "link.warn.veryLong": "Sehr lange Adresse: Anfang und Ende sind nie zugleich sichtbar.",
    "trust.badge": "100% lokal · nichts wird hochgeladen",
    "cam.zoneTitle": "Auf einen Code richten",
    "cam.zoneSub": "Liest während du bewegst. Nichts wird aufgezeichnet",
    "drop.orChoose": "Oder von diesem Computer wählen",
    "cam.title": "Live-Scan",
    "cam.freeze": "Einfrieren",
    "cam.resume": "Fortsetzen",
    "cam.frozen": "Bild steht. Zieh einen Rahmen um einen Code, um ihn zu lesen.",
    "qrgen.label": "Codes neu erzeugen",
    "qrgen.download": "Herunterladen ({n})",
    "qrgen.none": "Es gibt noch keinen Code zum Neuerzeugen.",
    "qrgen.working": "Die Codes werden gezeichnet…",
    "drop.folderMore": "Weiteren Ordner hinzufügen",
    "insp.keys": "Zieh einen Rahmen oder verschieb ihn an den Griffen. Scrollen bewegt, Pinch oder Strg+Rad zoomt, Leertaste und Ziehen verschiebt. Pfeile bewegen, Umschalt und Pfeile ändern die Größe, Enter liest, Esc schließt.",
    "res.summary": "{codes} Codes gelesen, davon {uniq} verschiedene.",
    "insp.zoomIn": "Vergrößern",
    "insp.zoomOut": "Verkleinern",
    "insp.fit": "Ganzes Bild anzeigen",
    "insp.fitShort": "Einpassen",
    "insp.open": "Auf den Code zeigen",
    "insp.title": "Auf den Code zeigen",
    "insp.hint": "Zieh einen Rahmen um den Code und lies dann diesen Bereich. Es wird nichts hochgeladen: der Ausschnitt wird hier gelesen, in diesem Tab.",
    "insp.rescan": "Diesen Bereich lesen",
    "insp.close": "Schließen",
    "insp.working": "Der Bereich wird gelesen...",
    "insp.found": "Gelesene Codes in diesem Bereich: {n}",
    "insp.none": "In diesem Bereich immer noch nichts Lesbares. Als Nächstes hilft ein näheres oder geraderes Foto.",
    "insp.prefilled": "Dieser Rahmen ist die Stelle, an der der Scanner einen Code gesehen hat. Korrigier ihn, falls er danebenliegt.",
    "app.tagline": "QR-Leser",
    "nav.source": "Quelltext",

    "hero.title": "Einen ganzen Ordner QR-Codes auf einmal scannen, oder live",
    "hero.sub": "Andere Leser nehmen ein Bild nach dem anderen. Hier ziehen Sie einen ganzen Ordner hinein, oder ein einzelnes Foto, oder ein ZIP. Sie bekommen jeden Code aus jedem Bild, mit der Datei dazu.",
    "hero.trust": "Nichts wird hochgeladen. Alles läuft hier, auf Ihrem Computer.",

    "tab.images": "Bilder",
    "tab.camera": "Kamera",

    "drop.title": "Hierher ziehen, oder auswählen",
    "drop.sub": "Ein Foto, ein Ordner, mehrere Ordner, oder ein ZIP",
    "drop.browse": "Dateien wählen",
    "drop.folder": "Ordner wählen",
    "drop.paste": "Bild einfügen",
    "drop.shoot": "Foto aufnehmen",

    "cam.off": "Die Kamera ist aus.<br>Richten Sie sie auf einen Code, er wird sofort gelesen.",
    "cam.start": "Kamera einschalten",
    "cam.stop": "Kamera ausschalten",
    "cam.looking": "Suche nach einem Code…",
    "cam.denied": "Kamerazugriff wurde abgelehnt.",
    "cam.none": "Hier ist keine Kamera verfügbar.",
    "cam.read": "Bisher gelesene Codes: {n}",

    "res.title": "Ergebnisse",
    "res.private": "100% privat · läuft in Ihrem Browser",
    "res.empty": "Gelesene Codes erscheinen hier.",
    "res.nothing": "Da ist nichts Lesbares drin. Es braucht Bilder.",
    "res.search": "In den Codes suchen…",
    "res.noMatch": "Kein Ergebnis passt zu dieser Suche.",
    "res.noCode": "Kein Code gefunden",
    "res.detected": "Code gefunden, nicht lesbar",
    "engine.loading": "Leser wird gestartet",
    "engine.ready": "Leser bereit",

    "work.files": "{n} Dateien",
    "stat.images": "Bilder",
    "stat.with": "mit Code",
    "stat.codes": "Codes",
    "stat.unique": "eindeutig",
    "stat.unread": "ungelesen",
    "stat.without": "ohne Code",
    "stat.unopened": "nicht geöffnet",

    "act.copyAll": "Alles kopieren",
    "act.copy": "kopieren",
    "act.copied": "kopiert",
    "act.download": "Herunterladen",
    "act.clear": "Leeren",
    "act.cancel": "Abbrechen",
    "act.clearAsk": "Alle bisher gelesenen Ergebnisse verwerfen?",
    "act.open": "Öffnen",
    "act.saveContact": "Kontakt speichern",
    "act.reveal": "Anzeigen",
    "act.hide": "Verbergen",

    "rename.pattern": "Neuer Name",
    "rename.code": "Der Inhalt des Codes",
    "rename.short": "Der nützliche Teil des Codes",
    "rename.nameCode": "Ursprünglicher Name + Code",
    "rename.keep": "Ursprüngliche Namen behalten",
    "rename.zip": "ZIP herunterladen ({n})",
    "rename.none": "Kein Bild hier hat einen Code, aus dem ein Name werden könnte.",
    "rename.preview": "wird gespeichert als",

    "dupe.badge": "in {n} Bildern",

    "err.advice": "Versuchen Sie es näher, mit dem Code gerade und gleichmäßig beleuchtet. Oder schneiden Sie eng darum zu.",
    "err.unopenable": "nicht lesbar: nicht unterstütztes Format oder beschädigte Datei",
    "err.fileAdvice": "Meist genügt es, sie in PNG oder JPEG umzuwandeln. Die lokale App liest Formate, die dieser Browser nicht öffnet.",

    "adv.localTitle": "Die lokale Anwendung läuft",
    "adv.localOn": "Eine lokale Kopie des Programms antwortet, diese Seite kann also mit den Dateien dort arbeiten, wo sie liegen.",
    "adv.scan": "Auf der Festplatte suchen",
    "adv.paths": "Ordner oder Dateien, einer pro Zeile",
    "adv.recreate": "QR-Bilder neu erzeugen",
    "adv.organize": "In with_qr / without_qr einsortieren",
    "adv.delete": "Bilder ohne Code löschen",
    "adv.confirmOrganize": "Jedes gefundene Bild in einen with_qr / without_qr Ordner daneben verschieben?",
    "adv.confirmDelete": "Jedes gefundene Bild ohne QR-Code endgültig löschen. Das lässt sich nicht rückgängig machen. Fortfahren?",
    "adv.scanFirst": "Suchen Sie zuerst auf der Festplatte.",

    "foot.privacy": "Ihre Bilder verlassen dieses Gerät nie.",

    "kind.url": "Link", "kind.wifi": "WLAN-Netz", "kind.contact": "Kontakt",
    "kind.payment": "Zahlung", "kind.email": "E-Mail", "kind.phone": "Telefonnummer",
    "kind.sms": "Nachricht", "kind.location": "Ort", "kind.event": "Termin",
    "kind.crypto": "Krypto-Adresse", "kind.otp": "Zwei-Faktor-Einrichtung",
    "kind.reference": "Referenz", "kind.text": "Text",

    "f.site": "Seite", "f.reference": "Referenz", "f.address": "Adresse",
    "f.network": "Netz", "f.security": "Sicherheit", "f.password": "Passwort",
    "f.name": "Name", "f.phone": "Telefon", "f.email": "E-Mail", "f.company": "Firma",
    "f.payee": "Empfänger", "f.iban": "IBAN", "f.amount": "Betrag",
    "f.subject": "Betreff", "f.message": "Nachricht", "f.number": "Nummer",
    "f.latitude": "Breite", "f.longitude": "Länge",
    "f.title": "Titel", "f.starts": "Beginn", "f.ends": "Ende", "f.where": "Wo",
    "f.account": "Konto", "f.issuer": "Dienst", "f.algorithm": "Algorithmus",
    "f.secret": "Geheimer Schlüssel", "f.content": "Inhalt",
  };

  S.pt = {
    "cam.settings": "Definições",
    "cam.found": "{n} encontrados",
    "res.compact": "Compacta",
    "act.exportAs": "Exportar neste formato",
    "qrgen.as": "Recriar os códigos neste formato",
    "res.more": "Mais",
    "res.moreHelp": "Outros formatos, e recriar os códigos como imagens",
    "cam.flip": "Espelhar",
    "cam.flipHelp": "Algumas câmaras entregam a imagem já espelhada. Esta página nunca a espelha; usa isto se a tua o fizer.",
    "cam.auto": "Auto",
    "cam.autoHelp": "Congela a imagem sozinho assim que vê um código, e depois lê-o como deve ser",
    "cam.closer": "Há um código no enquadramento mas é pequeno demais. Aproxima-te.",
    "cam.aim": "Aponta a câmara para um código QR",
    "cam.help": "Lê sozinha enquanto aponta. Congela a imagem para desenhar um retângulo à volta de um código difícil.",
    "cam.reading": "A ler…",
    "cam.checking": "A ler com atenção o que está no enquadramento…",
    "cam.autoGot": "Lidos {n} de {found}",
    "cam.autoNone": "Aí não há nada legível. Aproxima-te, endireita-o, ou desenha tu uma caixa.",
    "cam.device": "Câmara",
    "cam.deviceHelp": "Um iPhone ligado por Câmara de Continuidade aparece aqui como qualquer outra câmara",
    "cam.switch": "Mudar de câmara",
    "act.details": "Detalhes",
    "stat.toRead": "por ler",
    "res.filters": "Filtrar",
    "res.export": "Exportar",
    "rename.toggle": "Renomear os ficheiros primeiro",
    "row.flag": "Marcar para verificar",
    "row.unflag": "Retirar a marca",
    "filter.flagged": "Marcados",
    "csv.loaded": "{n} códigos de {file}, coluna «{col}»",
    "csv.clear": "Remover",
    "csv.noHeader": "sem cabeçalho, usada a primeira coluna",
    "csv.skipped": "{n} linhas vazias ignoradas",
    "filter.kind": "Tipo",
    "filter.kindAll": "Qualquer tipo",
    "stat.uniqueHelp": "Uma linha por conteúdo distinto: duas fotos do mesmo código contam uma vez",
    "rename.example": "Exemplo: {name}",
    "drop.keyboard": "Também podes arrastar ficheiros para aqui, ou usar os botões abaixo",
    "work.progress": "A ler {done} de {total} imagens",
    "work.now": "Agora: {name}",
    "work.pause": "Pausa",
    "work.resume": "Retomar",
    "work.paused": "Em pausa. Faltam {left}",
    "work.slow": "{name} está a demorar: é grande ou difícil de ler",
    "work.done": "{n} imagens terminadas",
    "link.title": "Para onde leva este código",
    "link.goes": "Esta ligação abre",
    "link.full": "Endereço completo",
    "link.open": "Abrir",
    "link.cancel": "Não abrir",
    "link.warn.userinfo": "O endereço esconde o site verdadeiro antes de um @. Abre a parte DEPOIS do @, não a que lês primeiro.",
    "link.warn.punycode": "O nome do site está em forma codificada: pode imitar outro nome letra a letra.",
    "link.warn.insecure": "Sem cifra. O que escreveres nesse site viaja em aberto.",
    "link.warn.ipHost": "Um endereço numérico em vez de um nome de site.",
    "link.warn.manyLabels": "Uma longa cadeia de nomes: o site verdadeiro é a parte mesmo antes do fim.",
    "link.warn.veryLong": "Endereço muito longo: o início e o fim nunca estão juntos no ecrã.",
    "trust.badge": "100% local · nada é enviado",
    "cam.zoneTitle": "Aponte para um código",
    "cam.zoneSub": "Lê enquanto move. Nada é gravado",
    "drop.orChoose": "Ou escolha deste computador",
    "cam.title": "Leitura ao vivo",
    "cam.freeze": "Congelar",
    "cam.resume": "Retomar",
    "cam.frozen": "Imagem parada. Arraste uma caixa à volta de um código para o ler.",
    "qrgen.label": "Recriar os códigos",
    "qrgen.download": "Descarregar ({n})",
    "qrgen.none": "Ainda não há nenhum código para recriar.",
    "qrgen.working": "A desenhar os códigos…",
    "drop.folderMore": "Adicionar outra pasta",
    "insp.keys": "Arraste uma caixa, ou mova-a pelas pegas. Role para se deslocar, faça pinça ou ctrl+roda para ampliar, espaço e arrastar para deslocar. As setas movem, shift e setas redimensionam, Enter lê, Esc fecha.",
    "res.summary": "{codes} códigos lidos, {uniq} deles diferentes.",
    "insp.zoomIn": "Aumentar",
    "insp.zoomOut": "Diminuir",
    "insp.fit": "Ver a imagem toda",
    "insp.fitShort": "Ajustar",
    "insp.open": "Aponte para o código",
    "insp.title": "Aponte para o código",
    "insp.hint": "Arraste uma caixa à volta do código e depois leia essa área. Nada é enviado: o recorte é lido aqui, neste separador.",
    "insp.rescan": "Ler esta área",
    "insp.close": "Fechar",
    "insp.working": "A ler essa área...",
    "insp.found": "Códigos lidos nessa área: {n}",
    "insp.none": "Nessa área continua a não haver nada legível. O passo seguinte é uma foto mais perto ou mais direita.",
    "insp.prefilled": "Esta caixa é onde o scanner viu um código. Ajuste-a se estiver ao lado.",
    "app.tagline": "leitor QR",
    "nav.source": "Código fonte",

    "hero.title": "Digitalize uma pasta inteira de códigos QR de uma vez, ou ao vivo",
    "hero.sub": "Outros leitores tratam uma foto de cada vez. Aqui arrasta uma pasta inteira, ou uma só foto, ou um zip. Obtém todos os códigos de todas as imagens, com o ficheiro de onde vêm.",
    "hero.trust": "Nada é enviado. Funciona tudo aqui, no seu computador.",

    "tab.images": "Imagens",
    "tab.camera": "Câmara",

    "drop.title": "Arraste para aqui, ou escolha",
    "drop.sub": "Uma foto, uma pasta, várias pastas, ou um zip",
    "drop.browse": "Escolher ficheiros",
    "drop.folder": "Escolher pasta",
    "drop.paste": "Colar uma imagem",
    "drop.shoot": "Tirar uma foto",

    "cam.off": "A câmara está desligada.<br>Aponte para um código e ele é lido em direto.",
    "cam.start": "Ligar a câmara",
    "cam.stop": "Desligar a câmara",
    "cam.looking": "À procura de um código…",
    "cam.denied": "Permissão da câmara recusada.",
    "cam.none": "Não há câmara disponível aqui.",
    "cam.read": "Códigos lidos até agora: {n}",

    "res.title": "Resultados",
    "res.private": "100% privado · funciona no seu navegador",
    "res.empty": "Os códigos que ler aparecem aqui.",
    "res.nothing": "Ali dentro não há nada para ler. São precisas imagens.",
    "res.search": "Procurar dentro dos códigos…",
    "res.noMatch": "Nenhum resultado corresponde a essa procura.",
    "res.noCode": "Nenhum código encontrado",
    "res.detected": "Código encontrado, não foi possível lê-lo",
    "engine.loading": "a iniciar o leitor",
    "engine.ready": "leitor pronto",

    "work.files": "{n} ficheiros",
    "stat.images": "imagens",
    "stat.with": "com código",
    "stat.codes": "códigos",
    "stat.unique": "únicos",
    "stat.unread": "por ler",
    "stat.without": "sem código",
    "stat.unopened": "não abertos",

    "act.copyAll": "Copiar tudo",
    "act.copy": "copiar",
    "act.copied": "copiado",
    "act.download": "Descarregar",
    "act.clear": "Limpar",
    "act.cancel": "Cancelar",
    "act.clearAsk": "Deitar fora todos os resultados lidos até agora?",
    "act.open": "Abrir",
    "act.saveContact": "Guardar contacto",
    "act.reveal": "Mostrar",
    "act.hide": "Esconder",

    "rename.pattern": "Novo nome",
    "rename.code": "O conteúdo do código",
    "rename.short": "A parte útil do código",
    "rename.nameCode": "Nome original + código",
    "rename.keep": "Manter os nomes originais",
    "rename.zip": "Descarregar ZIP ({n})",
    "rename.none": "Nenhuma imagem aqui tem um código de onde tirar o nome.",
    "rename.preview": "será guardado como",

    "dupe.badge": "em {n} imagens",

    "err.advice": "Tente de novo mais perto, com o código direito e bem iluminado. Ou corte justo à volta dele.",
    "err.unopenable": "não foi possível ler: formato não suportado ou ficheiro danificado",
    "err.fileAdvice": "Normalmente basta convertê-lo para PNG ou JPEG. A app local lê formatos que este navegador não abre.",

    "adv.localTitle": "A aplicação local está a correr",
    "adv.localOn": "Uma cópia local do programa está a responder, por isso esta página pode trabalhar sobre os ficheiros onde estão.",
    "adv.scan": "Analisar no disco",
    "adv.paths": "Pastas ou ficheiros, um por linha",
    "adv.recreate": "Recriar as imagens QR",
    "adv.organize": "Arrumar em with_qr / without_qr",
    "adv.delete": "Apagar as imagens sem código",
    "adv.confirmOrganize": "Mover cada imagem analisada para uma pasta with_qr / without_qr ao lado dela?",
    "adv.confirmDelete": "Apagar definitivamente cada imagem analisada sem código QR. Não se pode desfazer. Continuar?",
    "adv.scanFirst": "Analise primeiro no disco.",

    "foot.privacy": "As suas imagens nunca saem deste dispositivo.",

    "kind.url": "Ligação", "kind.wifi": "Rede Wi-Fi", "kind.contact": "Contacto",
    "kind.payment": "Pagamento", "kind.email": "Email", "kind.phone": "Número de telefone",
    "kind.sms": "Mensagem", "kind.location": "Localização", "kind.event": "Evento",
    "kind.crypto": "Endereço cripto", "kind.otp": "Configuração de dois fatores",
    "kind.reference": "Referência", "kind.text": "Texto",

    "f.site": "Site", "f.reference": "Referência", "f.address": "Endereço",
    "f.network": "Rede", "f.security": "Segurança", "f.password": "Palavra-passe",
    "f.name": "Nome", "f.phone": "Telefone", "f.email": "Email", "f.company": "Empresa",
    "f.payee": "Beneficiário", "f.iban": "IBAN", "f.amount": "Montante",
    "f.subject": "Assunto", "f.message": "Mensagem", "f.number": "Número",
    "f.latitude": "Latitude", "f.longitude": "Longitude",
    "f.title": "Título", "f.starts": "Início", "f.ends": "Fim", "f.where": "Onde",
    "f.account": "Conta", "f.issuer": "Serviço", "f.algorithm": "Algoritmo",
    "f.secret": "Chave secreta", "f.content": "Conteúdo",
  };


  // Simplified Chinese. Mandarin is the spoken language; the writing system is
  // the choice a page actually makes, and Simplified is the one the mainland
  // and Singapore read. Traditional would be a separate block under zh-Hant:
  // it is not a script conversion, some words differ outright.
  S.zh = {
    "cam.settings": "设置",
    "cam.found": "已找到 {n} 个",
    "res.compact": "紧凑",
    "act.exportAs": "以此格式导出",
    "qrgen.as": "以此格式重新生成二维码",
    "res.more": "更多",
    "res.moreHelp": "其他格式，以及把二维码还原成图片",
    "cam.flip": "镜像",
    "cam.flipHelp": "有些摄像头交出的画面已经是镜像的。本页从不镜像；如果你的摄像头会，就打开这个。",
    "cam.auto": "自动",
    "cam.autoHelp": "一看到二维码就自己抓取画面，然后仔细读取",
    "cam.closer": "画面里有二维码，但太小读不出来。请靠近一些。",
    "cam.aim": "把二维码对准这里",
    "cam.help": "对准时会自动读取。定格画面后，可以给难读的二维码框一个区域。",
    "cam.reading": "正在读取…",
    "cam.checking": "正在仔细读取画面里的内容…",
    "cam.autoGot": "读出 {found} 个中的 {n} 个",
    "cam.autoNone": "那里没有能读出的内容。靠近一点、放正，或者自己框一个区域。",
    "cam.device": "摄像头",
    "cam.deviceHelp": "通过“连续互通相机”连接的 iPhone 会像普通摄像头一样出现在这里",
    "cam.switch": "切换摄像头",
    "act.details": "详情",
    "stat.toRead": "待读取",
    "res.filters": "筛选",
    "res.export": "导出",
    "rename.toggle": "先重命名文件",
    "row.flag": "标记待查",
    "row.unflag": "取消标记",
    "filter.flagged": "已标记",
    "csv.loaded": "来自 {file} 的 {n} 个二维码，列“{col}”",
    "csv.clear": "移除它们",
    "csv.noHeader": "未找到表头，已使用第一列",
    "csv.skipped": "已跳过 {n} 个空行",
    "filter.kind": "类型",
    "filter.kindAll": "全部类型",
    "stat.uniqueHelp": "每个不同内容只算一行：同一个码的两张照片只算一次",
    "rename.example": "例如：{name}",
    "drop.keyboard": "也可以把文件拖到这里，或使用下面的按钮",
    "work.progress": "正在扫描第 {done} / {total} 张图片",
    "work.now": "当前：{name}",
    "work.pause": "暂停",
    "work.resume": "继续",
    "work.paused": "已暂停。还有 {left} 张待扫描",
    "work.slow": "{name} 有点慢：图片较大或较难读取",
    "work.done": "已完成 {n} 张图片",
    "link.title": "这个二维码会带你去哪里",
    "link.goes": "此链接将打开",
    "link.full": "完整地址",
    "link.open": "打开",
    "link.cancel": "不打开",
    "link.warn.userinfo": "地址在 @ 之前藏了真正的站点。打开的是 @ 之后的部分，而不是你先看到的那段。",
    "link.warn.punycode": "站点名以编码形式书写，可能逐字模仿另一个名字。",
    "link.warn.insecure": "未加密。在该站点输入的任何内容都会明文传输。",
    "link.warn.ipHost": "是一串裸地址，而不是站点名。",
    "link.warn.manyLabels": "一长串名字。真正的站点是结尾前的那一段。",
    "link.warn.veryLong": "地址非常长；它的开头和结尾无法同时显示。",
    "trust.badge": "100% 本地 · 不上传任何内容",
    "cam.zoneTitle": "把摄像头对准二维码",
    "cam.zoneSub": "移动中即可扫描，不会录制任何内容",
    "drop.orChoose": "或从这台电脑选择",
    "cam.title": "实时扫描",
    "cam.freeze": "定格",
    "cam.resume": "继续",
    "cam.frozen": "已定格。在二维码周围拖一个框来读取。",
    "qrgen.label": "重新生成二维码",
    "qrgen.download": "下载（{n}）",
    "qrgen.none": "还没有可以重新生成的二维码。",
    "qrgen.working": "正在绘制二维码…",
    "drop.folderMore": "再添加一个文件夹",
    "insp.keys": "拖出一个框，或拖动它的控制点。滚动平移，双指或 Ctrl+滚动缩放，按住空格拖动平移。方向键微调，Shift+方向键改变大小，回车读取，Esc 关闭。",
    "res.summary": "读出 {codes} 个二维码，其中 {uniq} 个不同。",
    "insp.zoomIn": "放大",
    "insp.zoomOut": "缩小",
    "insp.fit": "适应整张图片",
    "insp.fitShort": "适应",
    "insp.open": "指出二维码位置",
    "insp.title": "指出二维码位置",
    "insp.hint": "在二维码周围拖一个框，然后读取该区域。不会上传任何内容，裁剪出的部分就在这个标签页里读取。",
    "insp.rescan": "读取这个区域",
    "insp.close": "关闭",
    "insp.working": "正在读取该区域…",
    "insp.found": "在该区域读出的二维码：{n}",
    "insp.none": "该区域仍然没有可读的内容。下一步可以试试更近或更正的照片。",
    "insp.prefilled": "这个框是扫描器看到二维码的位置。如果不准，可以调整。",
    "app.tagline": "二维码扫描器",
    "nav.source": "源码",

    "hero.title": "一次扫描整个文件夹里的每一个二维码，也可以实时扫描",
    "hero.sub": "别的扫描器一次只看一张图。把整个文件夹、单张照片或一个压缩包拖到这里，你会得到每张图片里的每一个二维码，以及它来自哪个文件。",
    "hero.trust": "不上传任何内容。一切都在你的电脑上运行。",

    "tab.images": "图片",
    "tab.camera": "摄像头",

    "drop.title": "拖放，或浏览",
    "drop.sub": "一张照片、一个文件夹、多个文件夹，或一个压缩包",
    "drop.browse": "浏览文件",
    "drop.folder": "选择文件夹",
    "drop.paste": "粘贴图片",
    "drop.shoot": "拍照",

    "cam.off": "摄像头已关闭。<br>对准二维码即可实时读取。",
    "cam.start": "开启摄像头",
    "cam.stop": "关闭摄像头",
    "cam.looking": "正在寻找二维码…",
    "cam.denied": "摄像头权限被拒绝。",
    "cam.none": "这里没有可用的摄像头。",
    "cam.read": "已读出的二维码：{n}",

    "res.title": "结果",
    "res.private": "100% 私密 · 在你的浏览器中运行",
    "res.empty": "你扫描的二维码会显示在这里。",
    "res.nothing": "里面没有可读的内容。这里需要的是图片。",
    "res.search": "在二维码内容中搜索…",
    "res.noMatch": "没有符合该搜索的结果。",
    "res.noCode": "未找到二维码",
    "res.detected": "找到二维码，但读不出来",
    "engine.loading": "正在启动读取器",
    "engine.ready": "读取器就绪",

    "work.files": "{n} 个文件",
    "stat.images": "图片",
    "stat.with": "含二维码",
    "stat.codes": "二维码",
    "stat.unique": "去重",
    "stat.unread": "未读出",
    "stat.without": "无二维码",
    "stat.unopened": "未打开",

    "act.copyAll": "全部复制",
    "act.copy": "复制",
    "act.copied": "已复制",
    "act.download": "下载",
    "act.clear": "清空",
    "act.cancel": "取消",
    "act.clearAsk": "丢弃目前读出的所有结果？",
    "act.open": "打开",
    "act.saveContact": "保存联系人",
    "act.reveal": "显示",
    "act.hide": "隐藏",

    "rename.pattern": "新名称",
    "rename.code": "二维码内容",
    "rename.short": "二维码中有用的部分",
    "rename.nameCode": "原名 + 二维码",
    "rename.keep": "保留原来的名称",
    "rename.zip": "下载 ZIP（{n}）",
    "rename.none": "这里没有图片可以用二维码来命名。",
    "rename.preview": "将保存为",

    "dupe.badge": "出现在 {n} 张图片中",

    "err.advice": "请靠近一些再试，把二维码放平、光线均匀。或者紧贴它裁剪。",
    "err.unopenable": "无法读取：格式不支持，或文件已损坏",
    "err.fileAdvice": "转成 PNG 或 JPEG 通常可行。本地应用能读取这个浏览器读不了的格式。",

    "adv.localTitle": "本地应用正在运行",
    "adv.localOn": "本机的程序副本正在响应，因此本页也可以直接处理文件所在位置的文件。",
    "adv.scan": "扫描磁盘上的文件",
    "adv.paths": "文件夹或文件，每行一个",
    "adv.recreate": "重新生成二维码图片",
    "adv.organize": "整理为 with_qr / without_qr",
    "adv.delete": "删除没有二维码的图片",
    "adv.confirmOrganize": "把每张已扫描的图片移动到旁边的 with_qr / without_qr 文件夹？",
    "adv.confirmDelete": "将永久删除每张没有二维码的已扫描图片。此操作无法撤销。是否继续？",
    "adv.scanFirst": "请先扫描磁盘上的文件。",

    "foot.privacy": "你的图片绝不会离开这台设备。",

    "kind.url": "链接", "kind.wifi": "Wi-Fi 网络", "kind.contact": "联系人",
    "kind.payment": "付款", "kind.email": "电子邮件", "kind.phone": "电话号码",
    "kind.sms": "短信", "kind.location": "位置", "kind.event": "日程",
    "kind.crypto": "加密货币地址", "kind.otp": "两步验证设置",
    "kind.reference": "参考编号", "kind.text": "文本",

    "f.site": "站点", "f.reference": "编号", "f.address": "地址",
    "f.network": "网络", "f.security": "加密方式", "f.password": "密码",
    "f.name": "姓名", "f.phone": "电话", "f.email": "电子邮件", "f.company": "公司",
    "f.payee": "收款人", "f.iban": "IBAN", "f.amount": "金额",
    "f.subject": "主题", "f.message": "内容", "f.number": "号码",
    "f.latitude": "纬度", "f.longitude": "经度",
    "f.title": "标题", "f.starts": "开始", "f.ends": "结束", "f.where": "地点",
    "f.account": "账户", "f.issuer": "服务", "f.algorithm": "算法",
    "f.secret": "密钥", "f.content": "内容",
  };

  global.QR_STRINGS = S;
  global.QR_LANG_NAMES = NAMES;
})(typeof globalThis !== "undefined" ? globalThis : this);
